// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class ClientInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [Column("ClientID")]
    [StringLength(250)]
    [Unicode(false)]
    public string ClientId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ClientSecret { get; set; }

    public short? Type { get; set; }

    [Column("UserInfoID")]
    public long? UserInfoId { get; set; }

    [Column("URLInfoID")]
    public long? UrlinfoId { get; set; }

    public short? Status { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Role> Role { get; set; } = new List<Role>();

    [ForeignKey("UrlinfoId")]
    [InverseProperty("ClientInfo")]
    public virtual Urlinfo Urlinfo { get; set; }

    [InverseProperty("ClientInfo")]
    public virtual ICollection<UserClientLink> UserClientLink { get; set; } = new List<UserClientLink>();

    [ForeignKey("UserInfoId")]
    [InverseProperty("ClientInfo")]
    public virtual UserInfo UserInfo { get; set; }

    [InverseProperty("ClientInfo")]
    public virtual ICollection<UserLoginActivity> UserLoginActivity { get; set; } = new List<UserLoginActivity>();
}