// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class MenuInformation
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string MenuName { get; set; }

    [StringLength(500)]
    public string NavUrl { get; set; }

    [Column("HelpURL")]
    [StringLength(500)]
    public string HelpUrl { get; set; }

    /// <summary>
    /// Level of the menu
    /// </summary>
    public short? MenuLevel { get; set; }

    /// <summary>
    /// It will be set when it is loaded by default in child menus based parent menu (parentid)
    /// </summary>
    public bool? IsDefault { get; set; }

    /// <summary>
    /// It will decide oder
    /// </summary>
    public int? MenuOrder { get; set; }

    [Column("ParentID")]
    public long? ParentId { get; set; }

    /// <summary>
    /// 0-InActive,1-Active,3-Deleted
    /// </summary>
    public short? Status { get; set; }

    /// <summary>
    /// 0-Workflow Menu,1-Admin Menus,2-DashBoard Menus,3-Related to dynamicMenu
    /// </summary>
    public short? MenuType { get; set; }

    [Column("MenuBinID")]
    [MaxLength(18)]
    public byte[] MenuBinId { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<MenuInformation> InverseParent { get; set; } = new List<MenuInformation>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual MenuInformation Parent { get; set; }

    [InverseProperty("Menu")]
    public virtual ICollection<RolePrevileges> RolePrevileges { get; set; } = new List<RolePrevileges>();

    [InverseProperty("Menu")]
    public virtual ICollection<UserPrevileges> UserPrevileges { get; set; } = new List<UserPrevileges>();
}