// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class Role
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("ClientID")]
    public long? ClientId { get; set; }

    [Column("ParentID")]
    public long? ParentId { get; set; }

    public short? Status { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Role")]
    public virtual ClientInfo Client { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<Role> InverseParent { get; set; } = new List<Role>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual Role Parent { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolePrevileges> RolePrevileges { get; set; } = new List<RolePrevileges>();

    [InverseProperty("Role")]
    public virtual ICollection<UserClientLink> UserClientLink { get; set; } = new List<UserClientLink>();
}