// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class ServerInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ServerIP")]
    [StringLength(250)]
    [Unicode(false)]
    public string ServerIp { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Credentials { get; set; }

    public short? Type { get; set; }

    public short? ServerType { get; set; }

    public short? Status { get; set; }
}