// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

[Table("URLServerInfo")]
public partial class UrlserverInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("URLID")]
    public long? Urlid { get; set; }

    [Column("DomianServerID")]
    public long? DomianServerId { get; set; }

    [Column("DBServerID")]
    public long? DbserverId { get; set; }

    [Column("ReportServerID")]
    public long? ReportServerId { get; set; }

    [ForeignKey("Urlid")]
    [InverseProperty("UrlserverInfo")]
    public virtual Urlinfo Url { get; set; }
}