// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class UserInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string MiddleName { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string UserName { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Password { get; set; }

    public short? Status { get; set; }

    public bool? UserMergeEnabled { get; set; }

    [InverseProperty("UserInfo")]
    public virtual ICollection<ClientInfo> ClientInfo { get; set; } = new List<ClientInfo>();

    [InverseProperty("UserInfo")]
    public virtual ICollection<UserClientLink> UserClientLink { get; set; } = new List<UserClientLink>();

    [InverseProperty("IdNavigation")]
    public virtual UserCredentials UserCredentials { get; set; }

    [InverseProperty("UserInfo")]
    public virtual ICollection<UserLoginActivity> UserLoginActivity { get; set; } = new List<UserLoginActivity>();
}