// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class UserCorpLink
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserLinkID")]
    public long? UserLinkId { get; set; }

    [Column("CorpID")]
    [MaxLength(18)]
    public byte[] CorpId { get; set; }

    public short? Status { get; set; }

    [ForeignKey("UserLinkId")]
    [InverseProperty("UserCorpLink")]
    public virtual UserClientLink UserLink { get; set; }

    [InverseProperty("UserCorpLink")]
    public virtual ICollection<UserPclink> UserPclink { get; set; } = new List<UserPclink>();
}