// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

[Table("UserPCLink")]
public partial class UserPclink
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserCorpLinkID")]
    public long? UserCorpLinkId { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    public short Status { get; set; }

    [ForeignKey("UserCorpLinkId")]
    [InverseProperty("UserPclink")]
    public virtual UserCorpLink UserCorpLink { get; set; }
}