// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class UserCredentials
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string UserName { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Password { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("UserCredentials")]
    public virtual UserInfo IdNavigation { get; set; }
}