// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserMgmt.Domain.DataModel;

public partial class UserClientLink
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserInfoID")]
    public long? UserInfoId { get; set; }

    [Column("ClientInfoID")]
    public long? ClientInfoId { get; set; }

    public long? ReportTo { get; set; }

    public long? UserLevel { get; set; }

    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [Column("RoleID")]
    public long? RoleId { get; set; }

    [ForeignKey("ClientInfoId")]
    [InverseProperty("UserClientLink")]
    public virtual ClientInfo ClientInfo { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("UserClientLink")]
    public virtual Role Role { get; set; }

    [InverseProperty("GivenByNavigation")]
    public virtual ICollection<RolePrevileges> RolePrevileges { get; set; } = new List<RolePrevileges>();

    [InverseProperty("UserLink")]
    public virtual ICollection<UserCorpLink> UserCorpLink { get; set; } = new List<UserCorpLink>();

    [ForeignKey("UserInfoId")]
    [InverseProperty("UserClientLink")]
    public virtual UserInfo UserInfo { get; set; }

    [InverseProperty("GivenByNavigation")]
    public virtual ICollection<UserPrevileges> UserPrevilegesGivenByNavigation { get; set; } = new List<UserPrevileges>();

    [InverseProperty("UserLink")]
    public virtual ICollection<UserPrevileges> UserPrevilegesUserLink { get; set; } = new List<UserPrevileges>();
}