// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Common.App.Contracts;
using Dashboard.Analytics.Domain.DataModel;
using Microsoft.EntityFrameworkCore;

namespace Dashboard.Analytics.Infra.DbCon;

public partial class AnalyticsWHContext : DbContext,IAppDBContext
{
    public AnalyticsWHContext(DbContextOptions<AnalyticsWHContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ReqCorporation> ReqCorporations { get; set; }

    public virtual DbSet<ReqCustomFormula> ReqCustomFormulas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ReqCorporation>(entity =>
        {
            entity.ToTable("Req_Corporations");

            entity.HasIndex(e => e.ReqId, "ReqID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.ReqId).HasColumnName("ReqID");
        });

        modelBuilder.Entity<ReqCustomFormula>(entity =>
        {
            entity.ToTable("Req_CustomFormula");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CustomBinId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CustomBinID");
            entity.Property(e => e.CustomKeyName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ReqId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("ReqID");
            entity.Property(e => e.WidgetId).HasColumnName("WidgetID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}