// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Common.App.Contracts;
using Microsoft.EntityFrameworkCore;
using BankFeed.Domain.DataModel;
namespace BankFeed.Infra.DBCon;

public partial class BankFeedsContext : DbContext, IAppDBContext
{
    public BankFeedsContext(DbContextOptions<BankFeedsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AttentionRequiredBankAccounts> AttentionRequiredBankAccounts { get; set; }

    public virtual DbSet<FeedAccount> FeedAccount { get; set; }

    public virtual DbSet<FeedAccountMapping> FeedAccountMapping { get; set; }

    public virtual DbSet<FeedAccountMergeSettings> FeedAccountMergeSettings { get; set; }

    public virtual DbSet<FeedBankOrCreditAccounts> FeedBankOrCreditAccounts { get; set; }

    public virtual DbSet<FeedCategory> FeedCategory { get; set; }

    public virtual DbSet<FeedConnectionLog> FeedConnectionLog { get; set; }

    public virtual DbSet<FeedInstitute> FeedInstitute { get; set; }

    public virtual DbSet<FeedPossibleTransSharing> FeedPossibleTransSharing { get; set; }

    public virtual DbSet<FeedRule> FeedRule { get; set; }

    public virtual DbSet<FeedRuleDetails> FeedRuleDetails { get; set; }

    public virtual DbSet<FeedRuleMapping> FeedRuleMapping { get; set; }

    public virtual DbSet<FeedSettings> FeedSettings { get; set; }

    public virtual DbSet<FeedSynchSettings> FeedSynchSettings { get; set; }

    public virtual DbSet<FeedTimeZone> FeedTimeZone { get; set; }

    public virtual DbSet<FeedTransSharing> FeedTransSharing { get; set; }

    public virtual DbSet<FeedTransactionMapping> FeedTransactionMapping { get; set; }

    public virtual DbSet<FeedTransactionMappingDeleted> FeedTransactionMappingDeleted { get; set; }

    public virtual DbSet<FeedTransactionPossibleMatches> FeedTransactionPossibleMatches { get; set; }

    public virtual DbSet<FeedTransactions> FeedTransactions { get; set; }

    public virtual DbSet<FeedTransactionsDeleted> FeedTransactionsDeleted { get; set; }

    public virtual DbSet<ImportFormatSettings> ImportFormatSettings { get; set; }

    public virtual DbSet<NimbleAccountMergeSettings> NimbleAccountMergeSettings { get; set; }

    public virtual DbSet<ProviderInsChangeLog> ProviderInsChangeLog { get; set; }

    public virtual DbSet<ProviderRegister> ProviderRegister { get; set; }

    public virtual DbSet<Providers> Providers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AttentionRequiredBankAccounts>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Attentio__3214EC27B9AC35D3");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountLast4Digits)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.FileName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<FeedAccount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_AccountInfo");

            entity.HasIndex(e => new { e.InsId, e.Status }, "NonClusteredIndex-20260402-011316");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccEditName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccNumber)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccOffName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccSubType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AccountType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AvlBalance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BankAccId)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("BankAccID");
            entity.Property(e => e.CreatedOn).HasPrecision(0);
            entity.Property(e => e.FinancialAccId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("FinancialAccID");
            entity.Property(e => e.InsId).HasColumnName("InsID");
            entity.Property(e => e.ProviderStatus)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ProviderUpdatedOn).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SynchFrom).HasPrecision(0);

            entity.HasOne(d => d.Ins).WithMany(p => p.FeedAccount)
                .HasForeignKey(d => d.InsId)
                .HasConstraintName("FK_AccountInfo_InstituteInfo");
        });

        modelBuilder.Entity<FeedAccountMapping>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_AccountMapping");

            entity.HasIndex(e => new { e.CorpId, e.AccountId }, "NonClusteredIndex-20260402-011413");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.CorpId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorpID");
            entity.Property(e => e.FormatId).HasColumnName("FormatID");
            entity.Property(e => e.LastUpdatedOn).HasPrecision(0);
            entity.Property(e => e.LinkAccId)
                .HasDefaultValue(0L)
                .HasColumnName("LinkAccID");

            entity.HasOne(d => d.Format).WithMany(p => p.FeedAccountMapping)
                .HasForeignKey(d => d.FormatId)
                .HasConstraintName("FK_AccountMapping_ImportFormatSettings");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.FeedAccountMapping)
                .HasForeignKey<FeedAccountMapping>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountMapping_AccountInfo");
        });

        modelBuilder.Entity<FeedAccountMergeSettings>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FeedAccId).HasColumnName("FeedAccID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");

            entity.HasOne(d => d.FeedAcc).WithMany(p => p.FeedAccountMergeSettings)
                .HasForeignKey(d => d.FeedAccId)
                .HasConstraintName("FK_FeedAccountMergesettings_FeedAccount");
        });

        modelBuilder.Entity<FeedBankOrCreditAccounts>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength();

            entity.HasOne(d => d.FeedRule).WithMany(p => p.FeedBankOrCreditAccounts)
                .HasForeignKey(d => d.FeedRuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeedBankOrCreditAccounts_FeedRule");
        });

        modelBuilder.Entity<FeedCategory>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ParentCategoryId).HasColumnName("ParentCategoryID");
        });

        modelBuilder.Entity<FeedConnectionLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ConnectionLog");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FeedAccId).HasColumnName("FeedAccID");
            entity.Property(e => e.FormatId).HasColumnName("FormatID");
            entity.Property(e => e.LogDescription)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.LogSeqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("LogSeqID");
            entity.Property(e => e.LoggedOn).HasPrecision(0);

            entity.HasOne(d => d.FeedAcc).WithMany(p => p.FeedConnectionLog)
                .HasForeignKey(d => d.FeedAccId)
                .HasConstraintName("FK_ConnectionLog_AccountInfo");
        });

        modelBuilder.Entity<FeedInstitute>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_InstituteInfo");

            entity.HasIndex(e => e.ProviderRegId, "NonClusteredIndex-20260402-011433");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedOn).HasPrecision(0);
            entity.Property(e => e.DuplicateConnectionId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.InsName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.InsOffName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.InsProviderId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("InsProviderID");
            entity.Property(e => e.ProviderAccessId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("ProviderAccessID");
            entity.Property(e => e.ProviderRegId).HasColumnName("ProviderRegID");
            entity.Property(e => e.ProviderStatus)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.ServiceProvider)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.ProviderReg).WithMany(p => p.FeedInstitute)
                .HasForeignKey(d => d.ProviderRegId)
                .HasConstraintName("FK_InstituteInfo_ProviderRegister");
        });

        modelBuilder.Entity<FeedPossibleTransSharing>(entity =>
        {
            entity.ToTable("FeedPossibleTrans_Sharing");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdjustmentLinkId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("AdjustmentLinkID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BillNum)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CheckNo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("CheckNO");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.MergRefId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MergRefID");
            entity.Property(e => e.MergeLineId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MergeLineID");
            entity.Property(e => e.PayeeName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.ReqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ReqID");
            entity.Property(e => e.TransId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TransID");
            entity.Property(e => e.TransactionTypeName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<FeedRule>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BankOrCreditAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("BankOrCreditAccountID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.FeedAccId).HasColumnName("FeedAccID");
            entity.Property(e => e.Memo)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.RuleId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("RuleID");
            entity.Property(e => e.SetUpFor)
                .HasMaxLength(2000)
                .IsUnicode(false);

            entity.HasOne(d => d.FeedAcc).WithMany(p => p.FeedRule)
                .HasForeignKey(d => d.FeedAccId)
                .HasConstraintName("FK_FeedRule_AccountInfo");
        });

        modelBuilder.Entity<FeedRuleDetails>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FeedRuleId).HasColumnName("FeedRuleID");
            entity.Property(e => e.Val)
                .HasMaxLength(2000)
                .IsUnicode(false);

            entity.HasOne(d => d.FeedRule).WithMany(p => p.FeedRuleDetails)
                .HasForeignKey(d => d.FeedRuleId)
                .HasConstraintName("FK_FeedRuleDetails_FeedRule");
        });

        modelBuilder.Entity<FeedRuleMapping>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FeedRule__3214EC274285FFD4");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.AmountOrPercentageVal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CorpId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorpID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DepartmentID");
            entity.Property(e => e.FeedRuleId).HasColumnName("FeedRuleID");
            entity.Property(e => e.NameId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("NameID");
            entity.Property(e => e.PaymentMethodId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PaymentMethodID");
            entity.Property(e => e.PurposeId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("purposeID");

            entity.HasOne(d => d.FeedRule).WithMany(p => p.FeedRuleMapping)
                .HasForeignKey(d => d.FeedRuleId)
                .HasConstraintName("FK_FeedRuleMapping_FeedRule");
        });

        modelBuilder.Entity<FeedSettings>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
        });

        modelBuilder.Entity<FeedSynchSettings>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.SynchHour)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SynchTimeUtc).HasColumnName("SynchTimeUTC");
            entity.Property(e => e.TimeZoneId).HasColumnName("TimeZoneID");

            entity.HasOne(d => d.TimeZone).WithMany(p => p.FeedSynchSettings)
                .HasForeignKey(d => d.TimeZoneId)
                .HasConstraintName("FK_FeedSynchSettings_TimeZone");
        });

        modelBuilder.Entity<FeedTimeZone>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_TimeZone");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.IsDefault).HasDefaultValue(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<FeedTransSharing>(entity =>
        {
            entity.ToTable("FeedTrans_Sharing");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasPrecision(0);
            entity.Property(e => e.FeedTransId).HasColumnName("FeedTransID");
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.NameId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("NameID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.RefNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ReqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ReqID");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("TransactionID");
        });

        modelBuilder.Entity<FeedTransactionMapping>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.FeedTransId).HasColumnName("FeedTransID");
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.NameId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("NameID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.RefNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TransactionId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("TransactionID");

            entity.HasOne(d => d.FeedTrans).WithMany(p => p.FeedTransactionMapping)
                .HasForeignKey(d => d.FeedTransId)
                .HasConstraintName("FK_FeedTransactionMapping_FeedTransactionMapping");
        });

        modelBuilder.Entity<FeedTransactionMappingDeleted>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.FeedTransDelId).HasColumnName("FeedTransDelID");
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.NameId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("NameID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.RefNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TransactionId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("TransactionID");

            entity.HasOne(d => d.FeedTransDel).WithMany(p => p.FeedTransactionMappingDeleted)
                .HasForeignKey(d => d.FeedTransDelId)
                .HasConstraintName("FK_FeedTransactionMappingDeleted_Mapping");
        });

        modelBuilder.Entity<FeedTransactionPossibleMatches>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BillNum)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CheckNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.FeedTransId).HasColumnName("FeedTransID");
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.PayeeName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.TransactionId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("TransactionID");
            entity.Property(e => e.TransactionTypeName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.FeedTrans).WithMany(p => p.FeedTransactionPossibleMatches)
                .HasForeignKey(d => d.FeedTransId)
                .HasConstraintName("FK_FeedTransactionPossibleMatches_FeedTransactions");
        });

        modelBuilder.Entity<FeedTransactions>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CheckNumber)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.FeedAccId).HasColumnName("FeedAccID");
            entity.Property(e => e.FeedRuleId).HasColumnName("FeedRuleID");
            entity.Property(e => e.LogSeqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("LogSeqID");
            entity.Property(e => e.RunningBalance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransDate).HasPrecision(0);
            entity.Property(e => e.TransName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TransProviderId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("TransProviderID");
            entity.Property(e => e.TransType)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.FeedAcc).WithMany(p => p.FeedTransactions)
                .HasForeignKey(d => d.FeedAccId)
                .HasConstraintName("FK_FeedTransactions_AccountInfo1");

            entity.HasOne(d => d.FeedRule).WithMany(p => p.FeedTransactions)
                .HasForeignKey(d => d.FeedRuleId)
                .HasConstraintName("FK_FeedTransactions_FeedRule");
        });

        modelBuilder.Entity<FeedTransactionsDeleted>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CheckNumber)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ClientInfoId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientInfoID");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.FeedAccId).HasColumnName("FeedAccID");
            entity.Property(e => e.FeedRuleId).HasColumnName("FeedRuleID");
            entity.Property(e => e.FeedTransId).HasColumnName("FeedTransID");
            entity.Property(e => e.LogSeqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("LogSeqID");
            entity.Property(e => e.NimbleAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("NimbleAccountID");
            entity.Property(e => e.RunningBalance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransDate).HasPrecision(0);
            entity.Property(e => e.TransName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.TransProviderId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("TransProviderID");
            entity.Property(e => e.TransType)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.FeedRule).WithMany(p => p.FeedTransactionsDeleted)
                .HasForeignKey(d => d.FeedRuleId)
                .HasConstraintName("FK_FeedTransactionsDeleted_FeedRule");
        });

        modelBuilder.Entity<ImportFormatSettings>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AmountColumn1)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AmountColumn2)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.Date)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FormatName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FormatRefId)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.Memo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Num)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProviderRegId).HasColumnName("ProviderRegID");
            entity.Property(e => e.TemplatePath)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<NimbleAccountMergeSettings>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");
        });

        modelBuilder.Entity<ProviderInsChangeLog>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.InsId).HasColumnName("InsID");
            entity.Property(e => e.ProviderRegId).HasColumnName("ProviderRegID");
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.HasOne(d => d.Ins).WithMany(p => p.ProviderInsChangeLog)
                .HasForeignKey(d => d.InsId)
                .HasConstraintName("FK_ProviderInsChangeLog_InstituteInfo");

            entity.HasOne(d => d.ProviderReg).WithMany(p => p.ProviderInsChangeLog)
                .HasForeignKey(d => d.ProviderRegId)
                .HasConstraintName("FK_ProviderInsChangeLog_ProviderRegister");
        });

        modelBuilder.Entity<ProviderRegister>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("AccountID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.ClientName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CustomerId)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("CustomerID");
            entity.Property(e => e.ProviderId).HasColumnName("ProviderID");

            entity.HasOne(d => d.Provider).WithMany(p => p.ProviderRegister)
                .HasForeignKey(d => d.ProviderId)
                .HasConstraintName("FK_ProviderRegister_Providers");
        });

        modelBuilder.Entity<Providers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ProviderInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}