// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("1099ChangeMappingTempTable")]
[Index("ReqId", "VendorId", "AccountId", Name = "ReqID")]
public partial class _1099changeMappingTempTable
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("ReqID")]
    [StringLength(100)]
    [Unicode(false)]
    public string ReqId { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column("BoxLineID")]
    public int? BoxLineId { get; set; }
}