// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("Id", Name = "m_address$address_id_UNIQUE", IsUnique = true)]
public partial class Address
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Address1 { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Address2 { get; set; }

    public long? State { get; set; }

    public long? Country { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Business> Business { get; set; } = new List<Business>();

    [InverseProperty("DeliveryAddress")]
    public virtual ICollection<BusinessInfo> BusinessInfo { get; set; } = new List<BusinessInfo>();

    [InverseProperty("Address")]
    public virtual ICollection<Corporation> CorporationAddress { get; set; } = new List<Corporation>();

    [InverseProperty("LegalAddress")]
    public virtual ICollection<Corporation> CorporationLegalAddress { get; set; } = new List<Corporation>();

    [ForeignKey("Country")]
    [InverseProperty("Address")]
    public virtual Country CountryNavigation { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    [ForeignKey("State")]
    [InverseProperty("Address")]
    public virtual State StateNavigation { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Store> Store { get; set; } = new List<Store>();

    [InverseProperty("Address")]
    public virtual ICollection<User> User { get; set; } = new List<User>();

    [InverseProperty("Adress")]
    public virtual ICollection<VendorAddress> VendorAddress { get; set; } = new List<VendorAddress>();
}