// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("APFilterReq")]
public partial class ApfilterReq
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ReqID")]
    public long? ReqId { get; set; }

    public short? ReqSourceType { get; set; }

    public short? FilterColumnType { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Value { get; set; }

    /// <summary>
    /// 1-IDEqualls,2-StringEquals,3-NumberEqual,4-Startswith,5-Endswith,6-Greaterthan,7-lessthan,8-Ascsort,9-Descsort
    /// </summary>
    public short? OperationType { get; set; }
}