// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class ApprovalComments
{
    [Key]
    public long Id { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string Comment { get; set; }

    [MaxLength(18)]
    public byte[] CommentedBy { get; set; }

    public short? ApprovalLevel { get; set; }

    [Precision(0)]
    public DateTime? CommentDate { get; set; }

    [Column("AuditID")]
    public long? AuditId { get; set; }

    public short? Status { get; set; }
}