// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class AutoPostingInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column("PaymentMethodID")]
    [MaxLength(18)]
    public byte[] PaymentMethodId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    public DateTime RunDate { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public bool IsEntryPosted { get; set; }
}