// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BatchPrint
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("BatchID")]
    public int? BatchId { get; set; }

    [Column("JournalID")]
    [MaxLength(18)]
    public byte[] JournalId { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    public int? PrintCount { get; set; }

    public DateTime? CreatedOn { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? PrintedOn { get; set; }

    [MaxLength(18)]
    public byte[] PrintedBy { get; set; }

    [MaxLength(18)]
    public byte[] UpdatedBy { get; set; }

    public short? Status { get; set; }

    public long? Order { get; set; }

    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }
}