// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("BillInformationId", Name = "IDX_BillEntryPayments_BillINformationID")]
[Index("BillPaymentInformationId", Name = "IDX_BillEntryPayments_BillPaymentInformationID")]
public partial class BillEntryPayments
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    [Column("BillInformationID")]
    public long? BillInformationId { get; set; }

    [Column("BillPaymentID")]
    [MaxLength(18)]
    public byte[] BillPaymentId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PaidAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? OutStanding { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AdjustmentAmount { get; set; }

    [Column("AdjustID")]
    [MaxLength(18)]
    public byte[] AdjustId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Discount { get; set; }

    [Column("DiscountAccountID")]
    [MaxLength(18)]
    public byte[] DiscountAccountId { get; set; }

    public short? Status { get; set; }

    [Column("TransactioonID")]
    [MaxLength(18)]
    public byte[] TransactioonId { get; set; }

    [Column("AdjustTransactionID")]
    [MaxLength(18)]
    public byte[] AdjustTransactionId { get; set; }

    [Column("DiscountReconciliationID")]
    [MaxLength(18)]
    public byte[] DiscountReconciliationId { get; set; }

    [Column("DiscountTransactionID")]
    [MaxLength(18)]
    public byte[] DiscountTransactionId { get; set; }

    public short? DiscountReconStatus { get; set; }

    [Column("BillPaymentInformationID")]
    public long? BillPaymentInformationId { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DiscountMemo { get; set; }

    [ForeignKey("BillPaymentInformationId")]
    [InverseProperty("BillEntryPayments")]
    public virtual BillPaymentsInformation BillPaymentInformation { get; set; }
}