// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BillPaymentsInformation
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string CheckNo { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column("ReconciliationID")]
    [MaxLength(18)]
    public byte[] ReconciliationId { get; set; }

    public short? Reconstatus { get; set; }

    [Column("BillInformationID")]
    public long? BillInformationId { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column("StoreID")]
    [MaxLength(18)]
    public byte[] StoreId { get; set; }

    [StringLength(400)]
    [Unicode(false)]
    public string Memo { get; set; }

    [Column("AdjustTransactionID")]
    [MaxLength(18)]
    public byte[] AdjustTransactionId { get; set; }

    [Column("DiscountTransactionID")]
    [MaxLength(18)]
    public byte[] DiscountTransactionId { get; set; }

    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    public bool? DebitCredit { get; set; }

    [MaxLength(18)]
    public byte[] ApprovedBy { get; set; }

    public short? Status { get; set; }

    [Column("ContractID")]
    [MaxLength(18)]
    public byte[] ContractId { get; set; }

    [Precision(0)]
    public DateTime? EntryDate { get; set; }

    [MaxLength(18)]
    public byte[] AssignedTo { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [Column("PayMethodID")]
    [MaxLength(18)]
    public byte[] PayMethodId { get; set; }

    public short? PolCurStatus { get; set; }

    public short? ApprovalStatus { get; set; }

    public short? EntryType { get; set; }

    [Column("EPaymentStatus")]
    public short? EpaymentStatus { get; set; }

    [Precision(0)]
    public DateTime? VoidDate { get; set; }

    public bool? IsAttachement { get; set; }

    [InverseProperty("BillPaymentInformation")]
    public virtual ICollection<BillEntryPayments> BillEntryPayments { get; set; } = new List<BillEntryPayments>();
}