// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("BillEntryAIInformationDetails")]
public partial class BillEntryAiinformationDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Column("BillEntryInformationID")]
    public long BillEntryInformationId { get; set; }

    [Required]
    [Column("PurposeID")]
    [MaxLength(18)]
    public byte[] PurposeId { get; set; }

    [Column("AIPurposeName")]
    [StringLength(150)]
    [Unicode(false)]
    public string AipurposeName { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Type { get; set; }

    public short? Status { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    public bool? PurposeUpdated { get; set; }

    [ForeignKey("BillEntryInformationId")]
    [InverseProperty("BillEntryAiinformationDetails")]
    public virtual BillEntryInformation BillEntryInformation { get; set; }

    [ForeignKey("PurposeId")]
    [InverseProperty("BillEntryAiinformationDetails")]
    public virtual Purpose Purpose { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("BillEntryAiinformationDetails")]
    public virtual Ocrtransaction Transaction { get; set; }
}