// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("Status", "ApprovalStatus", Name = "IDX_BilLEntryInformation_Status")]
[Index("CorporationId", "RefType", Name = "IDX_BillEntryINformation_CorporationID")]
[Index("JournalEntryId", Name = "IDX_BillEntryInformation_JournalEntryID")]
public partial class BillEntryInformation
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Outstanding { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public short? DebitCredit { get; set; }

    public short? Status { get; set; }

    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Precision(0)]
    public DateTime? EntryDate { get; set; }

    [Column("CreditTermID")]
    [MaxLength(18)]
    public byte[] CreditTermId { get; set; }

    public short? RefType { get; set; }

    [Column("StoreID")]
    [MaxLength(18)]
    public byte[] StoreId { get; set; }

    [Column("ContractID")]
    [MaxLength(18)]
    public byte[] ContractId { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string EntryNumber { get; set; }

    [Precision(0)]
    public DateTime? BillDate { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [MaxLength(18)]
    public byte[] ApprovedBy { get; set; }

    [MaxLength(18)]
    public byte[] AssignedTo { get; set; }

    public short? ApprovalStatus { get; set; }

    [Column("MEMO")]
    [StringLength(800)]
    [Unicode(false)]
    public string Memo { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [Column("PayMethodID")]
    [MaxLength(18)]
    public byte[] PayMethodId { get; set; }

    public short? PolCurStatus { get; set; }

    public short? EntryType { get; set; }

    public bool? IsAttachement { get; set; }

    [Precision(0)]
    public DateTime? VoidDate { get; set; }

    public bool? IsHoldPayment { get; set; }

    [InverseProperty("BillEntryInformation")]
    public virtual ICollection<BillEntryAiinformationDetails> BillEntryAiinformationDetails { get; set; } = new List<BillEntryAiinformationDetails>();

    [InverseProperty("BillInfo")]
    public virtual ICollection<BillEntryInformationDetails> BillEntryInformationDetails { get; set; } = new List<BillEntryInformationDetails>();
}