// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BusinessRelatedExtension
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public short? SourceType { get; set; }

    public short? MarkupType { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? MarkupAmount { get; set; }

    [Column("FrequencyID")]
    [MaxLength(18)]
    public byte[] FrequencyId { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string InvoiceStartDate { get; set; }

    [ForeignKey("FrequencyId")]
    [InverseProperty("BusinessRelatedExtension")]
    public virtual Frequency Frequency { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("BusinessRelatedExtension")]
    public virtual Business IdNavigation { get; set; }
}