// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BusinessDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("BusinessID")]
    [MaxLength(18)]
    public byte[] BusinessId { get; set; }

    [Column("NameID")]
    [MaxLength(18)]
    public byte[] NameId { get; set; }

    public byte? MarkupType { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Percentage { get; set; }

    [ForeignKey("BusinessId")]
    [InverseProperty("BusinessDetails")]
    public virtual Business Business { get; set; }
}