// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BusinessPercentage
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("BusinessID")]
    [MaxLength(18)]
    public byte[] BusinessId { get; set; }

    public short? ManRecRepType { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public short? SourceType { get; set; }

    public short? CommissionType { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? CommissionAmount { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? OverheadAmount { get; set; }

    public short? Order { get; set; }

    public short? Status { get; set; }

    [ForeignKey("BusinessId")]
    [InverseProperty("BusinessPercentage")]
    public virtual Business Business { get; set; }
}