// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class Business
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    /// <summary>
    /// Transaction Source Type
    /// 0-----Customer,
    /// 1-----Vendor
    /// </summary>
    public short Type { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [Column("ContactID")]
    [MaxLength(18)]
    public byte[] ContactId { get; set; }

    [Column("AddressID")]
    [MaxLength(18)]
    public byte[] AddressId { get; set; }

    [Column("BankID")]
    [MaxLength(18)]
    public byte[] BankId { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] Terms { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CheckReference { get; set; }

    [Column("TaxID")]
    [StringLength(15)]
    [Unicode(false)]
    public string TaxId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? CreditLimit { get; set; }

    /// <summary>
    /// Enum---Status
    /// 0-----InActive,
    /// 1-----Active,
    /// 3-----Delete,
    /// As of now NULL is also Active
    /// </summary>
    public short Status { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? TaxPercentage { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ContactPersonName { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Column("ParentID")]
    [MaxLength(18)]
    public byte[] ParentId { get; set; }

    [Column("BID")]
    public long Bid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDateBy { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Business")]
    public virtual Account Account { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Business")]
    public virtual Address Address { get; set; }

    [InverseProperty("Business")]
    public virtual ICollection<BusinessDetails> BusinessDetails { get; set; } = new List<BusinessDetails>();

    [InverseProperty("IdNavigation")]
    public virtual BusinessInfo BusinessInfo { get; set; }

    [InverseProperty("Business")]
    public virtual ICollection<BusinessPercentage> BusinessPercentage { get; set; } = new List<BusinessPercentage>();

    [InverseProperty("IdNavigation")]
    public virtual BusinessRelatedExtension BusinessRelatedExtension { get; set; }

    [ForeignKey("ContactId")]
    [InverseProperty("Business")]
    public virtual Contact Contact { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("Business")]
    public virtual Corporation Corporation { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<Business> InverseParent { get; set; } = new List<Business>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual Business Parent { get; set; }

    [ForeignKey("Terms")]
    [InverseProperty("Business")]
    public virtual Frequency TermsNavigation { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<VendorAipurposeDetails> VendorAipurposeDetails { get; set; } = new List<VendorAipurposeDetails>();
}