// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class BusinessPreferences
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("BusinessID")]
    [MaxLength(18)]
    public byte[] BusinessId { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    public bool? FrachisePayment { get; set; }

    public bool? MakePaymentAlso { get; set; }
}