// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("Id", Name = "m_contact$contact_id_UNIQUE", IsUnique = true)]
public partial class Contact
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ContactName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Phone1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Phone2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Phone3 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string HomeNum { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AlternateNum { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Fax { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Website { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ContactTime { get; set; }

    [Column("VendorID")]
    [StringLength(200)]
    [Unicode(false)]
    public string VendorId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OwnerName { get; set; }

    [InverseProperty("Contact")]
    public virtual ICollection<Business> Business { get; set; } = new List<Business>();

    [InverseProperty("Contact")]
    public virtual ICollection<Corporation> Corporation { get; set; } = new List<Corporation>();

    [InverseProperty("Contact")]
    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    [InverseProperty("RelationContact")]
    public virtual ICollection<EmployeeDetails> EmployeeDetails { get; set; } = new List<EmployeeDetails>();

    [InverseProperty("Contact")]
    public virtual ICollection<Store> Store { get; set; } = new List<Store>();

    [InverseProperty("Contact")]
    public virtual ICollection<User> User { get; set; } = new List<User>();

    [InverseProperty("Contact")]
    public virtual ICollection<VendorAddress> VendorAddress { get; set; } = new List<VendorAddress>();
}