// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class CorporationYearEndProcess
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Precision(0)]
    public DateTime FromPeriod { get; set; }

    [Precision(0)]
    public DateTime ToPeriod { get; set; }

    /// <summary>
    /// Enum Status-
    /// 1----Active
    /// </summary>
    public bool ProcessStatus { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("CorporationYearEndProcess")]
    public virtual Corporation Corporation { get; set; }

    [ForeignKey("JournalEntryId")]
    [InverseProperty("CorporationYearEndProcess")]
    public virtual JournalEntry JournalEntry { get; set; }
}