// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class CorporationTaxSettings
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    public bool EnableTax { get; set; }

    public short Status { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("CorporationTaxSettings")]
    public virtual Corporation Corporation { get; set; }
}