// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("Id", Name = "m_corporation$corporation_id_UNIQUE", IsUnique = true)]
public partial class Corporation
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CorporationName { get; set; }

    [Column("COASettings")]
    public byte? Coasettings { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LegalName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DoingBusinessName { get; set; }

    [Column("ContactID")]
    [MaxLength(18)]
    public byte[] ContactId { get; set; }

    [Column("AddressID")]
    [MaxLength(18)]
    public byte[] AddressId { get; set; }

    [Column("FederalID")]
    [StringLength(15)]
    [Unicode(false)]
    public string FederalId { get; set; }

    [Column("CorporationStateID")]
    [StringLength(15)]
    [Unicode(false)]
    public string CorporationStateId { get; set; }

    [Column("WithholdingID")]
    [StringLength(15)]
    [Unicode(false)]
    public string WithholdingId { get; set; }

    [Column("UnEmploymentID")]
    [StringLength(15)]
    [Unicode(false)]
    public string UnEmploymentId { get; set; }

    [Column("LocalPayrolTaxID")]
    [StringLength(15)]
    [Unicode(false)]
    public string LocalPayrolTaxId { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string PeriodDateStart { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string PeriodDateEnd { get; set; }

    [Column(TypeName = "date")]
    public DateTime? IncorporationDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CorporationClosedDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? SalesStartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? BusinessEndDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? LockDate { get; set; }

    public short? FinancialYear { get; set; }

    /// <summary>
    /// Enum----Status
    /// 0-------InActive,
    /// 1-------Active,
    /// 3-------Delete
    /// </summary>
    public short Status { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string LockPasssword { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ShortName { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Column("CountryID")]
    public long? CountryId { get; set; }

    [Column("CompanyTypeID")]
    [MaxLength(18)]
    public byte[] CompanyTypeId { get; set; }

    [Column("LegalAddressID")]
    [MaxLength(18)]
    public byte[] LegalAddressId { get; set; }

    public bool? PurposeEnabled { get; set; }

    public bool? ProfitCenterEnabled { get; set; }

    public bool? CostCenterEnabled { get; set; }

    public byte? WeekDay { get; set; }

    public bool? IsTaxApplicable { get; set; }

    [Precision(0)]
    public DateTime? DueDate { get; set; }

    [Precision(0)]
    public DateTime? PayrollLiablityDueDate { get; set; }

    public byte? PropertyType { get; set; }

    public byte? HotelChain { get; set; }

    public byte? ServiceType { get; set; }

    public short? IsVoidDelete { get; set; }

    [Column("PMSType")]
    public short? Pmstype { get; set; }

    [Column("RegionID")]
    [MaxLength(18)]
    public byte[] RegionId { get; set; }

    [Column("PortpolioID")]
    [MaxLength(18)]
    public byte[] PortpolioId { get; set; }

    public short? SortOrder { get; set; }

    public int? Order { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string AccountCode { get; set; }

    public long? TotalAvailableRooms { get; set; }

    public long? TransNumber { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string BookkeepingMail { get; set; }

    public bool? IsAutoBill { get; set; }

    public byte? PostDays { get; set; }

    public short? EnableTaxInVendorMaster { get; set; }

    public bool? IsAutoApproval { get; set; }

    public bool? IsDualBrand { get; set; }

    public short? DefaultSettings { get; set; }

    [Column(TypeName = "date")]
    public DateTime? SaleStartDate { get; set; }
    public string BankfeedEmail { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("CorporationAddress")]
    public virtual Address Address { get; set; }

    [InverseProperty("Corporation")]
    public virtual ICollection<Business> Business { get; set; } = new List<Business>();

    [ForeignKey("ClientId")]
    [InverseProperty("Corporation")]
    public virtual User Client { get; set; }

    [ForeignKey("ContactId")]
    [InverseProperty("Corporation")]
    public virtual Contact Contact { get; set; }

    [InverseProperty("Corporation")]
    public virtual ICollection<CorporationTaxSettings> CorporationTaxSettings { get; set; } = new List<CorporationTaxSettings>();

    [InverseProperty("Corporation")]
    public virtual ICollection<CorporationYearEndProcess> CorporationYearEndProcess { get; set; } = new List<CorporationYearEndProcess>();

    [ForeignKey("CountryId")]
    [InverseProperty("Corporation")]
    public virtual Country Country { get; set; }

    [InverseProperty("Corporation")]
    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();
    [InverseProperty("Corporation")]
    public virtual ICollection<LoanShedule> LoanShedule { get; set; } = new List<LoanShedule>();

    [InverseProperty("Corporation")]
    public virtual ICollection<JournalEntry> JournalEntry { get; set; } = new List<JournalEntry>();

    [ForeignKey("LegalAddressId")]
    [InverseProperty("CorporationLegalAddress")]
    public virtual Address LegalAddress { get; set; }

    [InverseProperty("Corporation")]
    public virtual ICollection<Locking> Locking { get; set; } = new List<Locking>();

    [InverseProperty("Corporation")]
    public virtual ICollection<OcrjournalEntry> OcrjournalEntry { get; set; } = new List<OcrjournalEntry>();

    [InverseProperty("Corporation")]
    public virtual ICollection<PaymentBatchIssue> PaymentBatchIssue { get; set; } = new List<PaymentBatchIssue>();

    [InverseProperty("Corporation")]
    public virtual ICollection<Payroll> Payroll { get; set; } = new List<Payroll>();
    [InverseProperty("Corporation")]
    public virtual ICollection<PayrollDepartment> PayrollDepartment { get; set; } = new List<PayrollDepartment>();

    [InverseProperty("Corporation")]
    public virtual ICollection<PayrollDepartmentInfo> PayrollDepartmentInfo { get; set; } = new List<PayrollDepartmentInfo>();

    [InverseProperty("Corporation")]
    public virtual ICollection<Purpose> Purpose { get; set; } = new List<Purpose>();

    [InverseProperty("Corporation")]
    public virtual ICollection<Repetitive> Repetitive { get; set; } = new List<Repetitive>();

    [InverseProperty("Corporation")]
    public virtual ICollection<Store> Store { get; set; } = new List<Store>();

    [InverseProperty("Corporation")]
    public virtual ICollection<UserCorporation> UserCorporation { get; set; } = new List<UserCorporation>();

}