// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class CorporationBankDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column("AddressID")]
    [MaxLength(18)]
    public byte[] AddressId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string VoidAfter { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Memo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CheckNumber { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccountNumber { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RoutingNumber { get; set; }

    public byte? Status { get; set; }

    public DateTime? CreatedOn { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string BankName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CorpName { get; set; }

    [Column("DBAName")]
    [StringLength(100)]
    [Unicode(false)]
    public string Dbaname { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CorpAddress { get; set; }

    [Column("CorpCountryID")]
    public long? CorpCountryId { get; set; }

    [Column("CorpStateID")]
    public long? CorpStateId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CorpCity { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string CorpZipCode { get; set; }

    [Column("isAttached")]
    public short? IsAttached { get; set; }

    public DateTime? AttachedOn { get; set; }

    [MaxLength(18)]
    public byte[] AttachedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    [MaxLength(18)]
    public byte[] UpdatedBy { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string SignaturePath { get; set; }

    [Column("isDefault")]
    public bool? IsDefault { get; set; }

    public int? SignOrder { get; set; }
}