// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class Country
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int Status { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string CurrencyCode { get; set; }

    public short? IsDefault { get; set; }

    [InverseProperty("CountryNavigation")]
    public virtual ICollection<Address> Address { get; set; } = new List<Address>();

    [InverseProperty("Country")]
    public virtual ICollection<Corporation> Corporation { get; set; } = new List<Corporation>();

    [InverseProperty("Country")]
    public virtual ICollection<State> State { get; set; } = new List<State>();
}