// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class DepartmentConfig
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("ParentID")]
    [MaxLength(18)]
    public byte[] ParentId { get; set; }

    public int? DeptOrder { get; set; }

    /// <summary>
    /// 1=Departmental ,2=Non-Departmental
    /// </summary>
    public short? DeptType { get; set; }

    /// <summary>
    /// 0=Not Applicable,1=Room Caluculation,2=F&amp;B Calculations,3=Average Calculation,4=Other Without Stats
    /// </summary>
    public short? DailysaleType { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    public short Status { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [Precision(0)]
    public DateTime CreatedDate { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [InverseProperty("DeptConfig")]
    public virtual ICollection<GroupConfig> GroupConfig { get; set; } = new List<GroupConfig>();

    [InverseProperty("Parent")]
    public virtual ICollection<DepartmentConfig> InverseParent { get; set; } = new List<DepartmentConfig>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual DepartmentConfig Parent { get; set; }
}