// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class DeptConfig
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DeptName { get; set; }

    [Column("DeptParentID")]
    public long? DeptParentId { get; set; }

    public short? DeptOrder { get; set; }

    /// <summary>
    /// 0-Not Applicable,1-Room Caluculation,2-Average Calculation,3-Other Without Stats
    /// </summary>
    public short? DeptType { get; set; }

    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    public short? Status { get; set; }

    [ForeignKey("DeptParentId")]
    [InverseProperty("InverseDeptParent")]
    public virtual DeptConfig DeptParent { get; set; }

    [InverseProperty("DeptParent")]
    public virtual ICollection<DeptConfig> InverseDeptParent { get; set; } = new List<DeptConfig>();
}