// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class DirectDepositAuditInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("AuditID")]
    public long AuditId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CorporationLegalName { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string BankName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string OriginatorNo { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DataCenterNo { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string UpdatedColumns { get; set; }

    [ForeignKey("AuditId")]
    [InverseProperty("DirectDepositAuditInfo")]
    public virtual MasterBinAuditing Audit { get; set; }
}