// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class DirectDepositExportDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal BillAmt { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ExportedBy { get; set; }

    [MaxLength(18)]
    public byte[] LastExportedBy { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CreationNum { get; set; }

    public int? ExportedCnt { get; set; }

    [Column(TypeName = "date")]
    public DateTime? CreatedDate { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string MultipleCreationNoDisplay { get; set; }

    [Column("BID")]
    public long Bid { get; set; }

    public int IsFromReport { get; set; }

    [Column(TypeName = "date")]
    public DateTime? LatestCreatedDate { get; set; }

    public short? Status { get; set; }

    [Column("EFTREFNumber")]
    public short? Eftrefnumber { get; set; }

    [StringLength(15)]
    public string RepayStatus { get; set; }

    [StringLength(10)]
    public string RepayBatchNo { get; set; }

    [ForeignKey("JournalEntryId")]
    [InverseProperty("DirectDepositExportDetails")]
    public virtual JournalEntry JournalEntry { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("DirectDepositExportDetails")]
    public virtual Transaction Transaction { get; set; }
}