// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("DSDepositInfoDetails")]
public partial class DsdepositInfoDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("DSDepositInfoID")]
    public long? DsdepositInfoId { get; set; }

    [Column("DailySalesReceiptID")]
    [MaxLength(18)]
    public byte[] DailySalesReceiptId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SaleDate { get; set; }

    [Column("LineID")]
    [MaxLength(18)]
    public byte[] LineId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LineName { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    public int? LineOrder { get; set; }

    public int? DisplayOrder { get; set; }

    public short? IsEditable { get; set; }

    public int? RowSet { get; set; }

    public short? Status { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Difference { get; set; }
}