// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EFTAuditInfo")]
public partial class EftauditInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("AuditID")]
    public long AuditId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FormatName { get; set; }

    public bool? IsColumnUpdated { get; set; }

    [ForeignKey("AuditId")]
    [InverseProperty("EftauditInfo")]
    public virtual MasterLongAuditing Audit { get; set; }
}