// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EFTColumns")]
public partial class Eftcolumns
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Name { get; set; }

    public short? Order { get; set; }

    /// <summary>
    /// 0-PaymentDetails,
    /// 1-VendorDetails,
    /// 2-PayorDetails
    /// </summary>
    public byte? Type { get; set; }

    public byte? Status { get; set; }

    [InverseProperty("Eftcolumn")]
    public virtual ICollection<EftformatDetails> EftformatDetails { get; set; } = new List<EftformatDetails>();
}