// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EFTFormatDetails")]
public partial class EftformatDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("EFTFormatID")]
    public long EftformatId { get; set; }

    [Column("EFTColumnID")]
    public long EftcolumnId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ColumnNameCust { get; set; }

    public short? ExcelCol { get; set; }

    public short? Status { get; set; }

    [ForeignKey("EftcolumnId")]
    [InverseProperty("EftformatDetails")]
    public virtual Eftcolumns Eftcolumn { get; set; }

    [ForeignKey("EftformatId")]
    [InverseProperty("EftformatDetails")]
    public virtual Eftformat Eftformat { get; set; }
}