// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class Employee
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("SSN")]
    [StringLength(16)]
    [Unicode(false)]
    public string Ssn { get; set; }

    [Column("AddressID")]
    [MaxLength(18)]
    public byte[] AddressId { get; set; }

    [Column("ContactID")]
    [MaxLength(18)]
    public byte[] ContactId { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    /// <summary>
    /// Enum   Staus--
    /// 1--Active,
    /// 0--Inactive,
    /// 3--Delete
    /// 
    /// </summary>
    public short? Status { get; set; }

    /// <summary>
    /// 1 for available for paychecks new frequency,
    /// 0 for exist in frequency
    /// </summary>
    public bool? AvailableStatus { get; set; }

    /// <summary>
    /// Enum--EmpOtherType-
    /// 2---Employees,
    /// 13--Others
    /// </summary>
    public short? Type { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? RefInfo { get; set; }

    [Column("MapID")]
    [MaxLength(18)]
    public byte[] MapId { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Employee")]
    public virtual Address Address { get; set; }

    [ForeignKey("ContactId")]
    [InverseProperty("Employee")]
    public virtual Contact Contact { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("Employee")]
    public virtual Corporation Corporation { get; set; }

    [InverseProperty("IdNavigation")]
    public virtual EmployeeDetails EmployeeDetails { get; set; }
}