// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class EmployeeDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    public byte? Salutation { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string MiddleName { get; set; }

    public byte? Gender { get; set; }

    [Column("DOB", TypeName = "datetime")]
    public DateTime? Dob { get; set; }

    public short? MaritalStatus { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CheckTobePrintedAs { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BankAccountNum { get; set; }

    [Column("BankID")]
    [MaxLength(18)]
    public byte[] BankId { get; set; }

    [Column("RelationID")]
    [MaxLength(18)]
    public byte[] RelationId { get; set; }

    [Column("RelationContactID")]
    [MaxLength(18)]
    public byte[] RelationContactId { get; set; }

    [Column("FrequencyID")]
    [MaxLength(18)]
    public byte[] FrequencyId { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string PayrollStartDate { get; set; }

    public DateTime? HireDate { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? JobEndDate { get; set; }

    public DateTime? ReleaseDate { get; set; }

    [Column("JobID")]
    [MaxLength(18)]
    public byte[] JobId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string JobDescription { get; set; }

    public byte? TerminationType { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string TerminationReason { get; set; }

    public DateTime? LastDayWorked { get; set; }

    public bool? Billable { get; set; }

    [Column("LCAState", TypeName = "decimal(14, 2)")]
    public decimal? Lcastate { get; set; }

    [Column("LCAGC", TypeName = "decimal(14, 2)")]
    public decimal? Lcagc { get; set; }

    public bool? IsPensionPlanCovered { get; set; }

    public bool? IsTimesheetInfoUsed { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SickHrs { get; set; }

    public int? SickDays { get; set; }

    public DateTime? SickDate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string VacationHrs { get; set; }

    public int? Vacationdays { get; set; }

    [Column("vacationdate")]
    public DateTime? Vacationdate { get; set; }

    [Column("FederalFillingStatusID")]
    public byte? FederalFillingStatusId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? FederalAllowances { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? FederalWithHolding { get; set; }

    [Column("StateWorkedID")]
    public long? StateWorkedId { get; set; }

    [Column("StateWithHoldingID")]
    public long? StateWithHoldingId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? StateAllowances { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? StateWithHolding { get; set; }

    [Column("ISStateSUI")]
    public bool? IsstateSui { get; set; }

    [Column("IsStateSDI")]
    public bool? IsStateSdi { get; set; }

    [Column("IsLivingSUI")]
    public bool? IsLivingSui { get; set; }

    [Column("IsLivingSDI")]
    public bool? IsLivingSdi { get; set; }

    public bool? IsMedicare { get; set; }

    public bool? IsSocialSecurity { get; set; }

    public bool? IsAdvanceIncomeCredit { get; set; }

    public bool? IsFederalUnempTax { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("IsUSCitizen")]
    public bool? IsUscitizen { get; set; }

    public bool? IsI9onfile { get; set; }

    [Column("I9ExpirationDate")]
    public DateTime? I9expirationDate { get; set; }

    public byte? JobType { get; set; }

    public int? WorkingMaritalStatus { get; set; }

    public int? StateMaritalStatus { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string StatePersonalExemptions { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? StateDependentExemptions { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? StateNoofExemoptions { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string WorkPersonalExemptions { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? WorkDependentExemptions { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? WorkNoofExemoptions { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string RateCode { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string WorkAnnualCompensation { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string StateAnnualCompensation { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? WorkExtraWithholding { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? WorkAllowances { get; set; }

    [Column("PayrollDepartmentID")]
    [MaxLength(18)]
    public byte[] PayrollDepartmentId { get; set; }

    [ForeignKey("FrequencyId")]
    [InverseProperty("EmployeeDetails")]
    public virtual Frequency Frequency { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("EmployeeDetails")]
    public virtual Employee IdNavigation { get; set; }

    [ForeignKey("RelationContactId")]
    [InverseProperty("EmployeeDetails")]
    public virtual Contact RelationContact { get; set; }

    [ForeignKey("StateWithHoldingId")]
    [InverseProperty("EmployeeDetailsStateWithHoldingNavigation")]
    public virtual State StateWithHoldingNavigation { get; set; }

    [ForeignKey("StateWorkedId")]
    [InverseProperty("EmployeeDetailsStateWorked")]
    public virtual State StateWorked { get; set; }
}