// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EPaymentsBatchVoidDeleteLog")]
public partial class EpaymentsBatchVoidDeleteLog
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("EBatchLogID")]
    public long? EbatchLogId { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    /// <summary>
    /// 2=Voided/3=Deleted
    /// </summary>
    public short? Status { get; set; }

    public short? IssuedCount { get; set; }

    [ForeignKey("EbatchLogId")]
    [InverseProperty("EpaymentsBatchVoidDeleteLog")]
    public virtual EpaymentsBatchLog EbatchLog { get; set; }
}