// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EPaymentsBatch")]
public partial class EpaymentsBatch
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    public long BatchNumber { get; set; }

    [Precision(0)]
    public DateTime IntiationDate { get; set; }

    [MaxLength(18)]
    public byte[] AssignedTo { get; set; }

    public short? IssuedCount { get; set; }

    /// <summary>
    /// 1=Entered,2=Verified ,3=Approved ,4=Processing,5=Paid/Exported/Uploaded
    /// </summary>
    public short Status { get; set; }

    public short ApprovalLevel { get; set; }

    [Precision(0)]
    public DateTime CreatedDate { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    public long? FormatId { get; set; }

    [Column("BatchIssueID")]
    public long? BatchIssueId { get; set; }

    [Column("DDType")]
    public int? Ddtype { get; set; }

    [InverseProperty("EpaymentsBatch")]
    public virtual ICollection<EpaymentsBatchDetails> EpaymentsBatchDetails { get; set; } = new List<EpaymentsBatchDetails>();

    [InverseProperty("EpaymentsBatch")]
    public virtual ICollection<EpaymentsBatchLog> EpaymentsBatchLog { get; set; } = new List<EpaymentsBatchLog>();

    [ForeignKey("FormatId")]
    [InverseProperty("EpaymentsBatch")]
    public virtual Eftformat Format { get; set; }
}