// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("EPaymentsBatchLog")]
public partial class EpaymentsBatchLog
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("EPaymentsBatchID")]
    public long? EpaymentsBatchId { get; set; }

    /// <summary>
    /// 1=Create/2=Update/3=Delete
    /// </summary>
    public short? ActionType { get; set; }

    public short? Status { get; set; }

    [Precision(0)]
    public DateTime CreatedDate { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [StringLength(750)]
    [Unicode(false)]
    public string LogInfo { get; set; }

    [ForeignKey("EpaymentsBatchId")]
    [InverseProperty("EpaymentsBatchLog")]
    public virtual EpaymentsBatch EpaymentsBatch { get; set; }

    [InverseProperty("EbatchLog")]
    public virtual ICollection<EpaymentsBatchVoidDeleteLog> EpaymentsBatchVoidDeleteLog { get; set; } = new List<EpaymentsBatchVoidDeleteLog>();
}