// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class FortePaymentsSchedule
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public short SourceType { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column("BusinessTokenID")]
    public long BusinessTokenId { get; set; }

    public short? Status { get; set; }

    [Column("RefID")]
    [MaxLength(18)]
    public byte[] RefId { get; set; }

    public short? RefType { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string PayToken { get; set; }

    [Precision(0)]
    public DateTime? Date { get; set; }

    public short? Type { get; set; }

    [Column("TransactionID")]
    [StringLength(100)]
    [Unicode(false)]
    public string TransactionId { get; set; }

    public bool? IsFromAutoPayments { get; set; }

    [Column("TargetID")]
    [MaxLength(18)]
    public byte[] TargetId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string ForteStatus { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AuthCode { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string RemindmeBeforeMail { get; set; }

    public int? RemindmeBefore { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Number { get; set; }

    [ForeignKey("BusinessTokenId")]
    [InverseProperty("FortePaymentsSchedule")]
    public virtual BusinessTokenDetails BusinessToken { get; set; }
}