// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("fundtransferFilterReq")]
public partial class FundtransferFilterReq
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ReqID")]
    public long? ReqId { get; set; }

    public short? FilterColumnType { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Value { get; set; }

    public short OperationType { get; set; }
}