// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class GroupConfig
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("ParentID")]
    [MaxLength(18)]
    public byte[] ParentId { get; set; }

    public int? GroupOrder { get; set; }

    /// <summary>
    /// 1=Income , 2=Expense ,3=CostOfGoodsSold ,4=Profit
    /// </summary>
    public short GroupType { get; set; }

    [Column("DeptConfigID")]
    [MaxLength(18)]
    public byte[] DeptConfigId { get; set; }

    /// <summary>
    /// This field is used when the group type is Expense
    /// </summary>
    public bool? PayrollExpense { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    public int? RefOrder { get; set; }

    public short Status { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [Precision(0)]
    public DateTime CreatedDate { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [ForeignKey("DeptConfigId")]
    [InverseProperty("GroupConfig")]
    public virtual DepartmentConfig DeptConfig { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<GroupConfigAccSettings> GroupConfigAccSettings { get; set; } = new List<GroupConfigAccSettings>();

    [InverseProperty("Parent")]
    public virtual ICollection<GroupConfig> InverseParent { get; set; } = new List<GroupConfig>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual GroupConfig Parent { get; set; }
}