// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class GroupConfigAccSettings
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("GroupID")]
    [MaxLength(18)]
    public byte[] GroupId { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? FromAccountNumber { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? ToAccountNumber { get; set; }

    public int? AccounType { get; set; }

    /// <summary>
    /// 1 = Active , 2 = Delete
    /// </summary>
    public short Status { get; set; }

    [Required]
    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [Precision(6)]
    public DateTime CreatedDate { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(6)]
    public DateTime? ModifiedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string StrFromAccount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string StrToAccount { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("GroupConfigAccSettings")]
    public virtual GroupConfig Group { get; set; }
}