// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class ImportDocumentDetails
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("ImportDocumentID")]
    public int? ImportDocumentId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string FileName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FileSize { get; set; }

    public short? Status { get; set; }

    [ForeignKey("ImportDocumentId")]
    [InverseProperty("ImportDocumentDetails")]
    public virtual ImportDocument ImportDocument { get; set; }
}