// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class ImportDocument
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string FolderPath { get; set; }

    public short? Status { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string TypeName { get; set; }

    [InverseProperty("ImportDocument")]
    public virtual ICollection<ImportDocumentDetails> ImportDocumentDetails { get; set; } = new List<ImportDocumentDetails>();
}