// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class InterCompanyReferences
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("FromMainTransactionID")]
    [MaxLength(18)]
    public byte[] FromMainTransactionId { get; set; }

    [Column("FromTransactionID")]
    [MaxLength(18)]
    public byte[] FromTransactionId { get; set; }

    [Column("ToCreditTransactionID")]
    [MaxLength(18)]
    public byte[] ToCreditTransactionId { get; set; }

    [Column("ToDebitTransactionID")]
    [MaxLength(18)]
    public byte[] ToDebitTransactionId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column("FromJournalEntryID")]
    [MaxLength(18)]
    public byte[] FromJournalEntryId { get; set; }

    [Column("ToJournalEntryID")]
    [MaxLength(18)]
    public byte[] ToJournalEntryId { get; set; }

    [Column("ToCorporationID")]
    [MaxLength(18)]
    public byte[] ToCorporationId { get; set; }

    public int? Order { get; set; }

    public short? Status { get; set; }
}