// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class JournalChatInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Required]
    [Column("RoomID")]
    [StringLength(50)]
    [Unicode(false)]
    public string RoomId { get; set; }

    public short? Status { get; set; }

    public int? MessageUnreadCount { get; set; }
}