// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class LoanScheduleTransactions
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("LoanScheduleID")]
    [MaxLength(18)]
    public byte[] LoanScheduleId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? OriginalDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DueDate { get; set; }

    [Column("NetDaysID")]
    [MaxLength(18)]
    public byte[] NetDaysId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? BeginningBalance { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? MonthlyInterestRate { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? MonthlyAmount { get; set; }

    public short? InterestDaysMonths { get; set; }

    public short? InterestDaysYears { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? MonthlyInterestAmount { get; set; }

    [Column("SBAAmount", TypeName = "decimal(14, 2)")]
    public decimal? Sbaamount { get; set; }

    [Column("CDCAmount", TypeName = "decimal(14, 2)")]
    public decimal? Cdcamount { get; set; }

    [Column("CSAAmount", TypeName = "decimal(14, 2)")]
    public decimal? Csaamount { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? CustomAmount { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? PrincipalAmount { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? BalanceDueAmount { get; set; }

    public short? PaymentStatus { get; set; }

    public short? ReconStatus { get; set; }

    public short? Order { get; set; }

    public short? PaymentStatusType { get; set; }
}