// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class LoanScheduleTransactionDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("LoanScheduleTransactionID")]
    [MaxLength(18)]
    public byte[] LoanScheduleTransactionId { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column("PrincipalAccountID")]
    [MaxLength(18)]
    public byte[] PrincipalAccountId { get; set; }

    [Column("IntrestAccountID")]
    [MaxLength(18)]
    public byte[] IntrestAccountId { get; set; }

    [Column("SBAAccountID")]
    [MaxLength(18)]
    public byte[] SbaaccountId { get; set; }

    [Column("CDCAccountID")]
    [MaxLength(18)]
    public byte[] CdcaccountId { get; set; }

    [Column("CSAAccountID")]
    [MaxLength(18)]
    public byte[] CsaaccountId { get; set; }

    [Column("CustomAccountID")]
    [MaxLength(18)]
    public byte[] CustomAccountId { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    public short? SourceType { get; set; }

    public short? Status { get; set; }

    public short? Type { get; set; }
}