// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class LoanShedule
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "date")]
    public DateTime OriginalDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime PaymentStartDate { get; set; }

    [Column("NetDaysID")]
    [MaxLength(18)]
    public byte[] NetDaysId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string AccountNumberPayble { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal BeginningBalance { get; set; }

    public double MonthlyInterestRate { get; set; }

    public short? InterestDaysMonths { get; set; }

    public short? InterestDaysYears { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? MonthlyPayment { get; set; }

    [Column("SBAField")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sbafield { get; set; }

    [Column("SBAAmount", TypeName = "decimal(14, 2)")]
    public decimal? Sbaamount { get; set; }

    [Column("CDCField")]
    [StringLength(50)]
    [Unicode(false)]
    public string Cdcfield { get; set; }

    [Column("CDCAmount", TypeName = "decimal(14, 2)")]
    public decimal? Cdcamount { get; set; }

    [Column("CSAField")]
    [StringLength(50)]
    [Unicode(false)]
    public string Csafield { get; set; }

    [Column("CSAAmount", TypeName = "decimal(14, 2)")]
    public decimal? Csaamount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CustomField { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? CustomAmount { get; set; }

    public short? Status { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("LoanShedule")]
    public virtual Corporation Corporation { get; set; }

    //[ForeignKey("NetDaysId")]
    //[InverseProperty("LoanShedule")]
    //public virtual Frequency NetDays { get; set; }




}