// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class Locking
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    public byte LockPeriodType { get; set; }

    [Precision(0)]
    public DateTime FromDate { get; set; }

    [Precision(0)]
    public DateTime ToDate { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string TransactionType { get; set; }

    [Required]
    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [Precision(0)]
    public DateTime LockDate { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("Locking")]
    public virtual Corporation Corporation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Locking")]
    public virtual User User { get; set; }
}