// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class MasterLongAuditing
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("EntityID")]
    public long EntityId { get; set; }

    public short? EntityType { get; set; }

    [Precision(0)]
    public DateTime? ActionDate { get; set; }

    [MaxLength(18)]
    public byte[] ActionBy { get; set; }

    public short? ActionType { get; set; }

    [Column("IP")]
    [StringLength(250)]
    [Unicode(false)]
    public string Ip { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Browser { get; set; }

    [InverseProperty("Audit")]
    public virtual ICollection<EftauditInfo> EftauditInfo { get; set; } = new List<EftauditInfo>();

    [InverseProperty("Audit")]
    public virtual ICollection<RepayAuditInfo> RepayAuditInfo { get; set; } = new List<RepayAuditInfo>();
}