// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("OCRCreditTerm")]
public partial class OcrcreditTerm
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [MaxLength(18)]
    public byte[] CreditDays { get; set; }

    [Column(TypeName = "date")]
    public DateTime DueDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ShipDate { get; set; }

    [MaxLength(18)]
    public byte[] ShipVia { get; set; }

    [Column("ManagerID")]
    [MaxLength(18)]
    public byte[] ManagerId { get; set; }

    [Column("RecruiterID")]
    [MaxLength(18)]
    public byte[] RecruiterId { get; set; }

    [Column("RepresentativeID")]
    [MaxLength(18)]
    public byte[] RepresentativeId { get; set; }

    [Column("ContactID")]
    [MaxLength(18)]
    public byte[] ContactId { get; set; }

    [Column("AccContractID")]
    [MaxLength(18)]
    public byte[] AccContractId { get; set; }

    [ForeignKey("CreditDays")]
    [InverseProperty("OcrcreditTerm")]
    public virtual Frequency CreditDaysNavigation { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("OcrcreditTerm")]
    public virtual OcrjournalEntry IdNavigation { get; set; }
}