// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class PaymentBatchIssue
{
    [Key]
    public long Id { get; set; }

    public long? AvlBatchNumber { get; set; }

    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    public short? IssueType { get; set; }

    public short Status { get; set; }

    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    [Column("PaymethodID")]
    [MaxLength(18)]
    public byte[] PaymethodId { get; set; }

    public long? FormatId { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("PaymentBatchIssue")]
    public virtual Account Account { get; set; }

    [ForeignKey("CorporationId")]
    [InverseProperty("PaymentBatchIssue")]
    public virtual Corporation Corporation { get; set; }

    [ForeignKey("FormatId")]
    [InverseProperty("PaymentBatchIssue")]
    public virtual Eftformat Format { get; set; }

    [ForeignKey("PaymethodId")]
    [InverseProperty("PaymentBatchIssue")]
    public virtual MiscInfo Paymethod { get; set; }
}