// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("PCTransactions")]
public partial class Pctransactions
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column("RefID")]
    [MaxLength(18)]
    public byte[] RefId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Oustanding { get; set; }

    public bool DebitCredit { get; set; }
}