// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class ReconciliationMerge
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ReconciliationID")]
    [MaxLength(18)]
    public byte[] ReconciliationId { get; set; }

    public short? Type { get; set; }

    public short? Status { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [ForeignKey("ReconciliationId")]
    [InverseProperty("ReconciliationMerge")]
    public virtual Reconciliation Reconciliation { get; set; }

    [InverseProperty("ReconciliationMerge")]
    public virtual ICollection<ReconciliationMergeDetails> ReconciliationMergeDetails { get; set; } = new List<ReconciliationMergeDetails>();
}