// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class Reconciliation
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Precision(0)]
    public DateTime ReconciliationDate { get; set; }

    [Precision(0)]
    public DateTime StatementDate { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? OpeningBalance { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal StatementBalance { get; set; }

    [Required]
    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    /// <summary>
    /// Enum-----TransactionStatus-
    /// 6------Reconciled,
    /// 19-----ResumeReconcile
    /// </summary>
    public byte? Status { get; set; }

    /// <summary>
    /// Enum---ReconciliationType-
    /// 1---Automatic,
    /// 2---Manual
    /// </summary>
    public short? Type { get; set; }

    [Precision(0)]
    public DateTime? StartDate { get; set; }

    [Precision(0)]
    public DateTime? EndDate { get; set; }

    public int? TotalFeeds { get; set; }

    public int? Matched { get; set; }

    public int? UnMatched { get; set; }

    public short? IsAttachment { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Reconciliation")]
    public virtual Account Account { get; set; }

    [InverseProperty("Reconciliation")]
    public virtual ICollection<ReconciliationMerge> ReconciliationMerge { get; set; } = new List<ReconciliationMerge>();

    [InverseProperty("ReconciliationNavigation")]
    public virtual ICollection<Transaction> TransactionNavigation { get; set; } = new List<Transaction>();

    [ForeignKey("ReconciliationId")]
    [InverseProperty("Reconciliation")]
    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();
}