// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("Id", Name = "t_remind$remind_id_UNIQUE", IsUnique = true)]
public partial class Remind
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    public short Type { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Interval { get; set; }

    public short Status { get; set; }

    [InverseProperty("Remind")]
    public virtual ICollection<Repetitive> Repetitive { get; set; } = new List<Repetitive>();
}