// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class RepayAuditInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("AuditID")]
    public long AuditId { get; set; }

    [Column("ClientID")]
    [StringLength(250)]
    [Unicode(false)]
    public string ClientId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string ClientSecret { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string UpdateColumns { get; set; }

    [ForeignKey("AuditId")]
    [InverseProperty("RepayAuditInfo")]
    public virtual MasterLongAuditing Audit { get; set; }
}