// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class State
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("CountryID")]
    public long CountryId { get; set; }

    [Required]
    [StringLength(4)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(75)]
    [Unicode(false)]
    public string Name { get; set; }

    /// <summary>
    /// Enum----Status-
    /// 0-----InActive,
    /// 1--- -Active,
    /// 3-----Delete
    /// </summary>
    public byte Status { get; set; }

    [Column("SUI")]
    public byte? Sui { get; set; }

    [Column("SDI")]
    public byte? Sdi { get; set; }

    [InverseProperty("StateNavigation")]
    public virtual ICollection<Address> Address { get; set; } = new List<Address>();

    [ForeignKey("CountryId")]
    [InverseProperty("State")]
    public virtual Country Country { get; set; }

    [InverseProperty("StateWithHoldingNavigation")]
    public virtual ICollection<EmployeeDetails> EmployeeDetailsStateWithHoldingNavigation { get; set; } = new List<EmployeeDetails>();

    [InverseProperty("StateWorked")]
    public virtual ICollection<EmployeeDetails> EmployeeDetailsStateWorked { get; set; } = new List<EmployeeDetails>();

    [InverseProperty("State")]
    public virtual ICollection<UseTaxDetails> UseTaxDetails { get; set; } = new List<UseTaxDetails>();
}