// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class TemptableForBulkPrint
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("ReqID")]
    [StringLength(100)]
    public string ReqId { get; set; }

    [Column("JournalID")]
    [MaxLength(18)]
    public byte[] JournalId { get; set; }

    [Column("CorpID")]
    [MaxLength(18)]
    public byte[] CorpId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CheckNo { get; set; }

    public DateTime? CreatedOn { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    public short? Status { get; set; }

    public int? CheckOrder { get; set; }
}