// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Index("ReferenceId", "SourceId", "TargetId", "TargetType", Name = "Mixed")]
public partial class TransactionDetails
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Required]
    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Required]
    [Column("ReferenceID")]
    [MaxLength(18)]
    public byte[] ReferenceId { get; set; }

    public short ReferenceType { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal Amount { get; set; }

    public byte? Status { get; set; }

    [Precision(0)]
    public DateTime? Date { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    [Column("TargetID")]
    [MaxLength(18)]
    public byte[] TargetId { get; set; }

    public int? TargetType { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("TransactionDetails")]
    public virtual Transaction Transaction { get; set; }
}