// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class TransactionInvoice
{
    [Key]
    [Column("ID")]
    [MaxLength(18)]
    public byte[] Id { get; set; }

    [Column("InvoiceID")]
    [MaxLength(18)]
    public byte[] InvoiceId { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? Hrs { get; set; }

    [Column(TypeName = "decimal(17, 5)")]
    public decimal? Rate { get; set; }

    [Column(TypeName = "decimal(14, 2)")]
    public decimal? TaxRate { get; set; }

    [Column("SourceID")]
    [MaxLength(18)]
    public byte[] SourceId { get; set; }

    public byte? Status { get; set; }

    [Column("AccContractID")]
    [MaxLength(18)]
    public byte[] AccContractId { get; set; }

    public bool? BaseDebitCredit { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("TransactionInvoice")]
    public virtual Transaction IdNavigation { get; set; }
}