// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UserPreferenceSettings
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    public short? SettingValue { get; set; }

    [MaxLength(18)]
    public byte[] SettingType { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime ModifiedDate { get; set; }

    public short? IsDailySales { get; set; }

    public short? IsBill { get; set; }

    public short? EnableStatistics { get; set; }

    [Column("IsPO")]
    public short? IsPo { get; set; }

    public short? Type { get; set; }

    public bool? IsEnable { get; set; }

    public short? Value { get; set; }

    public bool? IsAutoEmail { get; set; }

    public short? AutoEmailType { get; set; }

    public bool? IsWhiteCheckMulStubs { get; set; }

    public bool? IsCorpLegalNameShow { get; set; }

    public short? IsAccountNameMulStubs { get; set; }

    public short? DisplayVendor { get; set; }

    public short? PreviewPanel { get; set; }

    public short? PrePrintFormat { get; set; }

    public short? EnableAutoAmountDistribution { get; set; }

    public short? StateFormat { get; set; }

    public short? AutoMemo { get; set; }

    public bool? IsConfirmDebit { get; set; }

    public bool? EnableManualMemo { get; set; }

    public bool? EnableCheckMemo { get; set; }

    public bool? EnableBillNumber { get; set; }

    public bool? EnableAccountNumber { get; set; }

    public short? PrePrintStubType { get; set; }

    public bool? EnableHeadAccount { get; set; }
}