// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UserDirectDepositDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [Column("DDUserAccess")]
    public short? DduserAccess { get; set; }

    public short? UserType { get; set; }

    [Column("MainUserID")]
    [MaxLength(18)]
    public byte[] MainUserId { get; set; }

    [Column("DDEmails")]
    public bool? Ddemails { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserDirectDepositDetails")]
    public virtual User User { get; set; }
}