// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UserSettings
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    public byte? ProfitCenterType { get; set; }

    public byte? PurposeType { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserSettings")]
    public virtual User User { get; set; }
}