// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

[Table("UserACHDetails")]
public partial class UserAchdetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UserID")]
    [MaxLength(18)]
    public byte[] UserId { get; set; }

    [Column("ACHType")]
    public short? Achtype { get; set; }

    public short? UserType { get; set; }

    [Column("MainUserID")]
    [MaxLength(18)]
    public byte[] MainUserId { get; set; }

    [Column("ACHEmails")]
    public bool? Achemails { get; set; }

    public short? ProviderType { get; set; }

    [Column("ACHAccess")]
    public short? Achaccess { get; set; }

    [Column("EFTAccess")]
    public short? Eftaccess { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserAchdetails")]
    public virtual User User { get; set; }
}