// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UseTaxDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UseTaxID")]
    public long? UseTaxId { get; set; }

    [Column("StateID")]
    public long? StateId { get; set; }

    public short Status { get; set; }

    [InverseProperty("UseTaxDetails")]
    public virtual ICollection<OcrtransactionTaxInfo> OcrtransactionTaxInfo { get; set; } = new List<OcrtransactionTaxInfo>();

    [ForeignKey("StateId")]
    [InverseProperty("UseTaxDetails")]
    public virtual State State { get; set; }

    [InverseProperty("UseTaxDetails")]
    public virtual ICollection<TransactionTaxInfo> TransactionTaxInfo { get; set; } = new List<TransactionTaxInfo>();

    [ForeignKey("UseTaxId")]
    [InverseProperty("UseTaxDetails")]
    public virtual UseTax UseTax { get; set; }

    [InverseProperty("UseTaxDetails")]
    public virtual ICollection<UseTaxRates> UseTaxRates { get; set; } = new List<UseTaxRates>();
}