// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UseTaxRates
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("UseTaxDetailsID")]
    public long? UseTaxDetailsId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Rate1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Rate2 { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public short Status { get; set; }

    public DateTime? EffectiveFrom2 { get; set; }

    public DateTime? EffectiveTo2 { get; set; }

    [InverseProperty("UseTaxRate")]
    public virtual ICollection<OcrtransactionTaxInfo> OcrtransactionTaxInfoUseTaxRate { get; set; } = new List<OcrtransactionTaxInfo>();

    [InverseProperty("UseTaxRateId2Navigation")]
    public virtual ICollection<OcrtransactionTaxInfo> OcrtransactionTaxInfoUseTaxRateId2Navigation { get; set; } = new List<OcrtransactionTaxInfo>();

    [InverseProperty("UseTaxRate")]
    public virtual ICollection<TransactionTaxInfo> TransactionTaxInfoUseTaxRate { get; set; } = new List<TransactionTaxInfo>();

    [InverseProperty("UseTaxRateId2Navigation")]
    public virtual ICollection<TransactionTaxInfo> TransactionTaxInfoUseTaxRateId2Navigation { get; set; } = new List<TransactionTaxInfo>();

    [ForeignKey("UseTaxDetailsId")]
    [InverseProperty("UseTaxRates")]
    public virtual UseTaxDetails UseTaxDetails { get; set; }
}