// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class UseTax
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string TaxName { get; set; }

    public short TaxType { get; set; }

    [Column("ParentID")]
    public long? ParentId { get; set; }

    [Required]
    [Column("ClientID")]
    [MaxLength(18)]
    public byte[] ClientId { get; set; }

    public short Status { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<UseTax> InverseParent { get; set; } = new List<UseTax>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual UseTax Parent { get; set; }

    [InverseProperty("UseTax")]
    public virtual ICollection<UseTaxDetails> UseTaxDetails { get; set; } = new List<UseTaxDetails>();
}