// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class VendorAddress
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("BusinessID")]
    [MaxLength(18)]
    public byte[] BusinessId { get; set; }

    [Required]
    [Column("AdressID")]
    [MaxLength(18)]
    public byte[] AdressId { get; set; }

    [Required]
    [Column("ContactID")]
    [MaxLength(18)]
    public byte[] ContactId { get; set; }

    [Column("BusinessTypeID")]
    [MaxLength(18)]
    public byte[] BusinessTypeId { get; set; }

    public short? Status { get; set; }

    public bool? IsDefault { get; set; }

    [ForeignKey("AdressId")]
    [InverseProperty("VendorAddress")]
    public virtual Address Adress { get; set; }

    [ForeignKey("ContactId")]
    [InverseProperty("VendorAddress")]
    public virtual Contact Contact { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<VendorContract> VendorContract { get; set; } = new List<VendorContract>();
}