// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class VendorTaxInfo
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? TaxPercentage { get; set; }

    public int? LineOrder { get; set; }

    public short? Status { get; set; }

    [Column("ContractID")]
    [MaxLength(18)]
    public byte[] ContractId { get; set; }

    [Column("PurposeID")]
    [MaxLength(18)]
    public byte[] PurposeId { get; set; }

    [ForeignKey("ContractId")]
    [InverseProperty("VendorTaxInfo")]
    public virtual VendorContract Contract { get; set; }

    [ForeignKey("PurposeId")]
    [InverseProperty("VendorTaxInfo")]
    public virtual Purpose Purpose { get; set; }
}