// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataModel.Domain.DataModel;

public partial class VendorAudit
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("AuditID")]
    public long? AuditId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("FederalID")]
    [StringLength(15)]
    [Unicode(false)]
    public string FederalId { get; set; }

    [Column("SSN")]
    [StringLength(16)]
    [Unicode(false)]
    public string Ssn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PrintCheckAs { get; set; }

    public bool? IsAutoBill { get; set; }

    [MaxLength(18)]
    public byte[] Terms { get; set; }

    [Column("PaymentMethodID")]
    [MaxLength(18)]
    public byte[] PaymentMethodId { get; set; }

    [Column("DDBranchNo")]
    [StringLength(10)]
    public string DdbranchNo { get; set; }

    [Column("DDInstitutionNo")]
    [StringLength(10)]
    public string DdinstitutionNo { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string UpdatedColumns { get; set; }

    public short? Status { get; set; }

    [Column("DDAccountNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string DdaccountNo { get; set; }

    [ForeignKey("AuditId")]
    [InverseProperty("VendorAudit")]
    public virtual MasterBinAuditing Audit { get; set; }
}