// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Common.App.Contracts;
using Microsoft.EntityFrameworkCore;
using ReportsAndConfig.Domain.DataModel;
namespace ReportsAndConfig.Infra.DBCon;

public partial class ReportsAndConfigContext : DbContext,IAppDBContext
{
    public ReportsAndConfigContext(DbContextOptions<ReportsAndConfigContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DepartmentConfig> DepartmentConfigs { get; set; }

    public virtual DbSet<GroupConfig> GroupConfigs { get; set; }

    public virtual DbSet<GroupConfigAccSetting> GroupConfigAccSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DepartmentConfig>(entity =>
        {
            entity.ToTable("DepartmentConfig");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_DepartmentConfig_DepartmentConfig");
        });

        modelBuilder.Entity<GroupConfig>(entity =>
        {
            entity.ToTable("GroupConfig");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.DeptConfigId).HasColumnName("DeptConfigID");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");

            entity.HasOne(d => d.DeptConfig).WithMany(p => p.GroupConfigs)
                .HasForeignKey(d => d.DeptConfigId)
                .HasConstraintName("FK_GroupConfig_DepartmentConfig");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_GroupConfig_GroupConfig1");
        });

        modelBuilder.Entity<GroupConfigAccSetting>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ModifiedDate).HasPrecision(0);

            entity.HasOne(d => d.Group).WithMany(p => p.GroupConfigAccSettings)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupConfigAccSettings_GroupConfigAccSettings");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}