// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Payable.Domain.DataModel;

public partial class BillPaymentImportMappingDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("BillPayImportID")]
    public long BillPayImportId { get; set; }

    [Required]
    [Column("BillJournalID")]
    [MaxLength(18)]
    public byte[] BillJournalId { get; set; }

    public short Status { get; set; }

    [ForeignKey("BillPayImportId")]
    [InverseProperty("BillPaymentImportMappingDetails")]
    public virtual BillPaymentImportDetails BillPayImport { get; set; }
}