// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Payable.Domain.DataModel;

public partial class BillPaymentImportDetails
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Precision(0)]
    public DateTime PayDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Number { get; set; }

    [Required]
    [Column("PaymethodID")]
    [MaxLength(18)]
    public byte[] PaymethodId { get; set; }

    [Required]
    [Column("BankAccountID")]
    [MaxLength(18)]
    public byte[] BankAccountId { get; set; }

    [Required]
    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    public short Status { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PaymentMemo { get; set; }

    [InverseProperty("BillPayImport")]
    public virtual ICollection<BillPaymentImportMappingDetails> BillPaymentImportMappingDetails { get; set; } = new List<BillPaymentImportMappingDetails>();
}