// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Payable.Domain.DataModel;

[Table("Req_BillForPayment")]
public partial class ReqBillForPayment
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ReqID")]
    public long? ReqId { get; set; }

    [Column("BillInfoID")]
    public long? BillInfoId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PaidAmount { get; set; }


    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Discount { get; set; }
}