<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NimbleProperty.$(MSBuildProjectName)</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Controllers\CoreAuthController.cs" />
    <Compile Remove="Controllers\WareHouseSynchController.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="nlog.config" />
  </ItemGroup>
  <ItemGroup>
    <None Include="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.7.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\02INFRA\CoreAccounting.Infra\CoreAccounting.Infra.csproj" />
    <ProjectReference Include="..\Common.API\Common.API\Common.API.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="BillEntry.htm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>