// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dashboard.Domain.DataModel;

public partial class WidgetPrivilegeDetails
{
    public long Id { get; set; }

    public long WidgetPrivId { get; set; }

    public long WidgetId { get; set; }

    public bool? IsView { get; set; }

    public bool? IsNavigate { get; set; }

    public bool? IsFormula { get; set; }

    public bool? IsDelete { get; set; }

    public virtual Widgets Widget { get; set; }

    public virtual WidgetPrivileges WidgetPriv { get; set; }
}