// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dashboard.Domain.DataModel;

public partial class WidgetCustomization
{
    public long Id { get; set; }

    public long? GroupType { get; set; }

    public long? IncomeDeptId { get; set; }

    public long? IncomeGroupId { get; set; }

    public long? AccountId { get; set; }

    public long? PayrollDeptId { get; set; }

    public long? CorpKey { get; set; }

    public long? CustomizationType { get; set; }

    public long? CustomeGroup { get; set; }
}