// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dashboard.Domain.DataModel;

public partial class WidgetUserSettings
{
    public long Id { get; set; }

    public long WidgetId { get; set; }

    public short DateFilterType { get; set; }

    public short? DateViewType { get; set; }

    public string CompValue { get; set; }

    public byte[] UserId { get; set; }

    public string ColumnValue { get; set; }

    public virtual Widgets Widget { get; set; }
}