// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dashboard.Domain.DataModel;

public partial class Widgets
{
    public long Id { get; set; }

    public string Name { get; set; }

    public short Type { get; set; }

    public short? SubType { get; set; }

    public short GroupType { get; set; }

    public bool IsGraphicalOrTable { get; set; }

    public bool IsRowsCustomized { get; set; }

    public bool IsColumnsCustomized { get; set; }

    public short DisplayWidth { get; set; }

    public short? DefaultFilterType { get; set; }

    public string DefaultComparisionType { get; set; }

    public short? DefaultDateViewType { get; set; }

    public short SortOrder { get; set; }

    public short Status { get; set; }

    public byte[] UserId { get; set; }

    public byte[] ClientId { get; set; }

    public short? SubGroup { get; set; }

    public virtual ICollection<WidgetFormulaSettings> WidgetFormulaSettings { get; set; } = new List<WidgetFormulaSettings>();

    public virtual ICollection<WidgetPrivilegeDetails> WidgetPrivilegeDetails { get; set; } = new List<WidgetPrivilegeDetails>();

    public virtual ICollection<WidgetUserSettings> WidgetUserSettings { get; set; } = new List<WidgetUserSettings>();
}