// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class AdjustOpeningBalance
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] ProfitCenter { get; set; }

    public string AdjustableAmount { get; set; }

    public DateTime? AsOfDate { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public byte[] UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}