// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class ApprovalPloicy
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public short? TransactionType { get; set; }

    public short? Status { get; set; }

    public virtual ICollection<ApprovalPloicyDetails> ApprovalPloicyDetails { get; set; } = new List<ApprovalPloicyDetails>();
}