// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigInputEntryArdetails
{
    public byte[] Id { get; set; }

    public byte[] DconfigIerevId { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] SourceId { get; set; }

    public short? SourceType { get; set; }

    public decimal? Amount { get; set; }

    public string Description { get; set; }

    public short? Status { get; set; }

    public int? Order { get; set; }

    public byte[] CrRefId { get; set; }

    public byte[] DrRefId { get; set; }
}