// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigInputEntryStatisticsDetails
{
    public byte[] Id { get; set; }

    public byte[] DconfigIesdid { get; set; }

    public string Description { get; set; }

    public long? Count { get; set; }

    public short? Status { get; set; }

    public int? Order { get; set; }
}