// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigDepartment
{
    public byte[] Id { get; set; }

    public string Name { get; set; }

    public short? Type { get; set; }

    public short? Status { get; set; }

    public short? DeptType { get; set; }

    public virtual ICollection<DailyConfigLine> DailyConfigLine { get; set; } = new List<DailyConfigLine>();
}