// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigGroup
{
    public byte[] Id { get; set; }

    public byte[] CorporationId { get; set; }

    public string Name { get; set; }

    public byte[] DepartmentId { get; set; }

    public byte[] ParentGroupId { get; set; }

    public long? Order { get; set; }

    public long? IncomeSubDepartmentId { get; set; }

    public short? Status { get; set; }

    public byte[] CommonMappingId { get; set; }

    public virtual ICollection<DailyConfigLine> DailyConfigLine { get; set; } = new List<DailyConfigLine>();

    public virtual ICollection<DailyConfigGroup> InverseParentGroup { get; set; } = new List<DailyConfigGroup>();

    public virtual DailyConfigGroup ParentGroup { get; set; }
}