// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigInputEntryReceipt
{
    public byte[] Id { get; set; }

    public byte[] DailyConfigInputId { get; set; }

    public byte[] SourceId { get; set; }

    public short? SourceType { get; set; }

    public decimal? Amount { get; set; }

    public short? Status { get; set; }

    public byte[] CaccountId { get; set; }

    public byte[] DaccountId { get; set; }

    public byte[] CreditRefId { get; set; }

    public byte[] DebitRefId { get; set; }

    public long Drid { get; set; }

    public virtual DailyConfigInputEntry DailyConfigInput { get; set; }
}