// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailySaleDefaults
{
    public long Id { get; set; }

    public byte[] GroupId { get; set; }

    public byte[] DepartmentId { get; set; }

    public short? DeptType { get; set; }

    public short? Type { get; set; }

    public int? DetailType { get; set; }

    public byte[] LineId { get; set; }

    public string DepartmentName { get; set; }

    public string ParentGroupName { get; set; }

    public string GroupName { get; set; }

    public string ItemName { get; set; }

    public int? ParentGroupOrder { get; set; }

    public int? GroupOrder { get; set; }

    public short? SourceType { get; set; }

    public long? Order { get; set; }

    public string Description { get; set; }

    public string TargetDescription { get; set; }

    public short? IsReadOnly { get; set; }
}