// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigLine
{
    public byte[] Id { get; set; }

    public byte[] CorporationId { get; set; }

    public string Name { get; set; }

    public byte[] DepartmentId { get; set; }

    public byte[] GroupId { get; set; }

    public long? Order { get; set; }

    public short? EnableAdroravg { get; set; }

    public bool? EnableNegative { get; set; }

    public bool? ExcludeFromTotals { get; set; }

    public bool? EnableMultiple { get; set; }

    public byte[] CreditAccountId { get; set; }

    public byte[] DebitAccountId { get; set; }

    public short? SourceType { get; set; }

    public byte[] SourceId { get; set; }

    public short? Status { get; set; }

    public byte[] CommonMappingId { get; set; }

    public byte? ServiceType { get; set; }

    public short? ExcludeFromActualDeposit { get; set; }

    public short? ArledgerType { get; set; }

    public short? IsVacantRooms { get; set; }

    public short? ArnetType { get; set; }

    public short? RoomType { get; set; }

    public short? AdjustNetAmountto { get; set; }

    public short? AdjustLedgerType { get; set; }

    public short? AdjustLedgerNet { get; set; }

    public short? AdjustLedgerWithAcountsOnlyLine { get; set; }

    public byte[] AdjustLedgerNetId { get; set; }

    public byte[] LaborStatisticsParentId { get; set; }

    public short? LaborStatisticsLineType { get; set; }

    public short? LaborStatisticsAvgLine { get; set; }

    public byte? IsHouseKeepingDepartment { get; set; }

    public long? LabourStatisticsGroupOrder { get; set; }

    public short? LaborActiveStatus { get; set; }

    public long Dlid { get; set; }

    public byte[] StoreId { get; set; }

    public byte[] CreditCardTypId { get; set; }

    public short? StatisticsCalculationType { get; set; }

    public virtual ICollection<DailyConfigInputEntryRevenue> DailyConfigInputEntryRevenue { get; set; } = new List<DailyConfigInputEntryRevenue>();

    public virtual DailyConfigDepartment Department { get; set; }

    public virtual DailyConfigGroup Group { get; set; }
}