// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DailyConfigInputEntry
{
    public byte[] Id { get; set; }

    public byte[] CorporationId { get; set; }

    public DateTime SaleDate { get; set; }

    public byte[] CashJournalId { get; set; }

    public byte[] RevenueJournalId { get; set; }

    public short? Status { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public byte[] ModofiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte[] ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public bool? IsConfigMismatch { get; set; }

    public short? ImportType { get; set; }

    public byte[] AssignedTo { get; set; }

    public short? ApprovalLevel { get; set; }

    public short? ApprovalStatus { get; set; }

    public short? IsAttachment { get; set; }

    public short? IsAutomatic { get; set; }

    public short? IsReimported { get; set; }

    public long Dcid { get; set; }

    public byte[] StoreId { get; set; }

    public long? RoomsCount { get; set; }

    public string Weather { get; set; }

    public virtual ICollection<DailyConfigInputEntryAr> DailyConfigInputEntryAr { get; set; } = new List<DailyConfigInputEntryAr>();

    public virtual ICollection<DailyConfigInputEntryReceipt> DailyConfigInputEntryReceipt { get; set; } = new List<DailyConfigInputEntryReceipt>();

    public virtual ICollection<DailyConfigInputEntryRevenue> DailyConfigInputEntryRevenue { get; set; } = new List<DailyConfigInputEntryRevenue>();

    public virtual ICollection<DailyConfigInputEntryStatistics> DailyConfigInputEntryStatistics { get; set; } = new List<DailyConfigInputEntryStatistics>();
}