// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DsCashCheckFilterReq
{
    public long Id { get; set; }

    public long ReqId { get; set; }

    public short? ReqSourceType { get; set; }

    public short? FilterColumnType { get; set; }

    public string Value { get; set; }

    public short OperationType { get; set; }
}