// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Dsdeposits
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public DateTime? DepositDate { get; set; }

    public string Memo { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? TotalDeposited { get; set; }

    public decimal? Difference { get; set; }

    public DateTime? CreatedOn { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public byte[] ModifiedBy { get; set; }

    public short? IsAttachment { get; set; }

    public string ReqId { get; set; }

    public byte[] AttachmentId { get; set; }

    public short? Status { get; set; }

    public byte[] StoreId { get; set; }

    public byte[] ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public byte[] AssignedTo { get; set; }

    public short? ApprovalLevel { get; set; }

    public short? ApprovalStatus { get; set; }

    public virtual ICollection<DsdepositInfo> DsdepositInfo { get; set; } = new List<DsdepositInfo>();
}