// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class DummyDailyConfigInputEntryRevStat
{
    public byte[] Id { get; set; }

    public byte[] Did { get; set; }

    public byte[] DailyConfigInputId { get; set; }

    public byte[] LineId { get; set; }

    public decimal? Amount { get; set; }

    public short? Status { get; set; }

    public short? Type { get; set; }

    public int? Order { get; set; }

    public string RequestId { get; set; }

    public byte[] CreditRefId { get; set; }

    public byte[] DebitRefId { get; set; }

    public byte[] CaccountId { get; set; }

    public byte[] DaccountId { get; set; }
}