// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Locking
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public byte LockPeriodType { get; set; }

    public DateTime FromDate { get; set; }

    public DateTime ToDate { get; set; }

    public string TransactionType { get; set; }

    public byte[] UserId { get; set; }

    public DateTime LockDate { get; set; }
}