// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Lookup
{
    public byte[] Id { get; set; }

    /// <summary>
    /// Role IDs from Role Table, Constant IDs for Sales
    /// </summary>
    public byte[] SourceId { get; set; }

    /// <summary>
    /// CLT-----------clone type
    /// RL-------------Role
    /// SR-------------sales registers
    /// CS-------------cash sales
    /// NCS-----------non cash sales
    /// SP-------------sales payins
    /// MR------------Motel Register
    /// GR-------------Gas Register
    /// CA-------------Cards
    /// GAC-----------Gas Accounts
    /// MSG-----------Messages
    /// PRP-----------purpose
    /// BNS-----------Business
    /// DPL-----------Dunkin P&amp;L
    /// Convenient-Convenient Sales
    /// CashType--- CashType
    /// Money-------Money
    /// Products-----Products
    /// Taxes---------Sales Taxes
    /// CND----------Credit Net Days
    /// CRD----------Cards
    /// SCLT---------Sales Cloning Types
    /// 
    /// </summary>
    public string Code { get; set; }

    public string Value { get; set; }

    public string Description { get; set; }

    public short? Order { get; set; }

    /// <summary>
    /// Enum------LookupSourceType-
    /// 1-----------Lookup
    /// 2-----------PayrollTax
    /// 3-----------GasTax
    /// 4-----------Account,
    /// 5-----------Role,
    /// 6---------- Business,
    /// 7---------- MessageGroup,
    /// 8--------- Purpose,
    /// 9---------Clone,
    /// 10--------SR 
    /// 11--------MR,
    /// 12--------GR,
    /// 13--------CS,
    /// 14--------NCS,
    /// 15--------SP,
    /// 16--------DunkinPL,
    /// 17--------User,
    /// 18--------News
    /// 19------Cards,
    /// 20------CreditNetDays,
    /// 21------Features,    
    /// 22------ConvenientSales,
    /// 23------Taxes,
    /// 24------MoneyInAndOut,
    /// 25------CashTypes,
    /// 26------CloneSettings,
    /// 27------Products
    /// </summary>
    public short? SourceType { get; set; }

    /// <summary>
    /// Enum---------Status-
    /// 0---------InActive,
    /// 1---------Active,
    /// 3---------Delete
    /// </summary>
    public short? Status { get; set; }

    public string SourceMappingXml { get; set; }
}