// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class MerchantReconciliation
{
    public long Id { get; set; }

    public string ReconRefId { get; set; }

    public string ReconLineRefId { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] Pcid { get; set; }

    public byte[] AccountId { get; set; }

    public DateTime FromDate { get; set; }

    public DateTime ToDate { get; set; }

    public string MerchantNumber { get; set; }

    public string MerchantName { get; set; }

    public DateTime StatementEndDate { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public byte[] ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public short Status { get; set; }

    public virtual ICollection<MerchantReconciliationDetail> MerchantReconciliationDetail { get; set; } = new List<MerchantReconciliationDetail>();
}