// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class MerchantCoapreference
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] Pcid { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] AdjustmentAccountId { get; set; }

    public byte[] ChargeBackAccountId { get; set; }

    public byte[] MerchantAccountId { get; set; }
}