// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class OtbforeCastDetails
{
    public long Id { get; set; }

    public long OtbforeCastId { get; set; }

    public DateTime SaleDate { get; set; }

    public int RoomsSold { get; set; }

    public int RoomsAvailable { get; set; }

    public decimal Adr { get; set; }

    public decimal Revenue { get; set; }

    public decimal RevPar { get; set; }

    public int TotalGuests { get; set; }

    public short Status { get; set; }

    public virtual OtbforeCastInfo OtbforeCast { get; set; }

    public virtual ICollection<OtbforeCastIndividualDetails> OtbforeCastIndividualDetails { get; set; } = new List<OtbforeCastIndividualDetails>();
}