// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class OtbforeCastInfo
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] StoreId { get; set; }

    public DateTime ForeCastReportDate { get; set; }

    public string CreatedByName { get; set; }

    public byte[] CreatedBy { get; set; }

    public short Otbtype { get; set; }

    public DateTime CreatedDate { get; set; }

    public short Status { get; set; }

    public string ImportRefId { get; set; }

    public virtual ICollection<OtbforeCastDetails> OtbforeCastDetails { get; set; } = new List<OtbforeCastDetails>();
}