// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class OtbforeCastIndividualDetails
{
    public long Id { get; set; }

    public long OtbforeCastDetailsId { get; set; }

    public short SourceType { get; set; }

    public int RoomsSold { get; set; }

    public int Guests { get; set; }

    public short Status { get; set; }

    public virtual OtbforeCastDetails OtbforeCastDetails { get; set; }
}