// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class PmscorporationMapping
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public string FacilityId { get; set; }

    public short? Status { get; set; }

    public short? Type { get; set; }

    public long? MapId { get; set; }

    public byte[] StoreId { get; set; }

    public string AmountReadFrom { get; set; }

    public string AliasFacilityId { get; set; }

    public virtual ICollection<PmscorporationMappindDetails> PmscorporationMappindDetails { get; set; } = new List<PmscorporationMappindDetails>();

    public virtual ICollection<UnMappedDailyConfigInputEntry> UnMappedDailyConfigInputEntry { get; set; } = new List<UnMappedDailyConfigInputEntry>();
}