// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class PmsclientInfo
{
    public long Id { get; set; }

    public byte[] ClientId { get; set; }

    public string ClientName { get; set; }

    public long? UrlId { get; set; }

    public short? Status { get; set; }
}