// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class PmscorporationMappindDetails
{
    public long Id { get; set; }

    public long PmscorpMappingId { get; set; }

    public long? PmsmappingId { get; set; }

    public byte[] LineId { get; set; }

    public int? Order { get; set; }

    public string AccountId { get; set; }

    public string AccountDescription { get; set; }

    public string PmscurrencyType { get; set; }

    public short? Status { get; set; }

    public short? Type { get; set; }

    public string Seq { get; set; }

    public short? DebitCreditMapping { get; set; }

    public string TransactionType { get; set; }

    public short? DeptType { get; set; }

    public short? IsEnding { get; set; }

    public string Category { get; set; }

    public string SubCategory { get; set; }

    public bool? IsConfigMismatch { get; set; }

    public short? IsNotRequired { get; set; }

    public short? SignMapping { get; set; }

    public virtual PmscorporationMapping PmscorpMapping { get; set; }

    public virtual ICollection<UnMappedDailyConfigInputEntry> UnMappedDailyConfigInputEntry { get; set; } = new List<UnMappedDailyConfigInputEntry>();
}