// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class PmsfacilityMapDetails
{
    public long Id { get; set; }

    public long? PmsfacilityMapId { get; set; }

    public string FileName { get; set; }

    public short? Status { get; set; }
}