// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Pmsinfo
{
    public long Id { get; set; }

    public string Pmsname { get; set; }

    public short? Pmstype { get; set; }

    public short? Status { get; set; }
}