// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Preferences
{
    public byte[] Id { get; set; }

    public byte[] UserId { get; set; }

    public byte[] CoporationId { get; set; }

    public byte[] BankAccountId { get; set; }

    public byte[] PayrollAccountId { get; set; }

    public bool? DcpbillMakePayment { get; set; }

    public short? Type { get; set; }

    public short? ShowPreview { get; set; }

    public short? Status { get; set; }

    public byte[] StoreId { get; set; }

    public bool? IsAutoApproval { get; set; }

    public string Ardifference { get; set; }
}