// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class ReqMerchantRecon
{
    public long Id { get; set; }

    public long? ReqId { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] Pcid { get; set; }

    public byte[] AccountId { get; set; }
}