// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Store
{
    public byte[] Id { get; set; }

    public byte[] CorporationId { get; set; }

    public string Name { get; set; }

    public string CustomerId { get; set; }

    public byte[] ContactId { get; set; }

    public byte[] AddressId { get; set; }

    public decimal? BaseRent { get; set; }

    public decimal? TaxEscrow { get; set; }

    public decimal? Deductions { get; set; }

    public decimal? PercentageRent { get; set; }

    public DateTime? StoreDateStart { get; set; }

    public DateTime? StoreDateEnd { get; set; }

    /// <summary>
    /// 1-DayWise
    /// </summary>
    public short SalesType { get; set; }

    /// <summary>
    /// Enum----Status-
    /// 0-----InActive,
    /// 1--- -Active,
    /// 3-----Delete
    /// </summary>
    public short Status { get; set; }

    public string PcNo { get; set; }

    public byte[] ParentStoreId { get; set; }

    public short? DefaultStore { get; set; }

    public short? Pmstype { get; set; }

    public string BookkeeperMail { get; set; }

    public int? TotalAvailableRooms { get; set; }

    public short? PropertyType { get; set; }

    public short? ServiceType { get; set; }

    public short? BrandName { get; set; }

    public short? DefaultSettings { get; set; }

    public DateTime? SaleStartDate { get; set; }

    public virtual ICollection<Store> InverseParentStore { get; set; } = new List<Store>();

    public virtual Store ParentStore { get; set; }

    public virtual ICollection<Transaction> Transaction { get; set; } = new List<Transaction>();
}