// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DailySales.Domain.DataModel;

public partial class Transaction
{
    public byte[] Id { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] JournalEntryId { get; set; }

    public byte[] ParentId { get; set; }

    public decimal Amount { get; set; }

    /// <summary>
    /// 0----Debit,
    /// 1----Credit
    /// </summary>
    public bool DebitCredit { get; set; }

    public DateTime TransactionDate { get; set; }

    /// <summary>
    /// Checks--------------Ref.Num,
    /// Bill Payments-------Ref.Num,
    /// DCP------------------null,
    /// Franchisee fee-----null,
    /// Loans----------------Ref. Num,
    /// Gas Bill--------------Ref Num,
    /// Receipts------------Ref Num,
    /// Customer receipt-Ref Num,
    /// Fund transfer------Ref Num,
    /// Bill Entry------------Ref Num,
    /// Invoice--------------null,
    /// Wage cost----------null,
    /// Paychecks----------checkno,
    /// Adhoc payment---null,
    /// Tax payment-------null,
    /// Other payment----null,
    /// Journal--------------null,
    /// YearEndProcess---null
    /// 
    /// </summary>
    public string ReferenceNumber { get; set; }

    public string Memo { get; set; }

    /// <summary>
    /// 0---InActive,
    /// 1---Active,
    /// 2---Void,
    /// 3---Delete,
    /// 4---Pending,
    /// 5---Completed,
    /// 6---Reconciled,
    /// 7---Locked,
    /// 8---RecurringReconciled,
    /// 9---RecurringLocked,
    /// 10--ReconcileLocked,
    /// 11--RecurringReconcileLocked,
    /// 12--CCFee,
    /// 13--Paid,
    /// 14--Unpaid,
    /// 15--WithoutCC,
    /// 16--NormalCC,
    /// 17--ReverseCC,
    /// 18--GasWithoutAmount,
    /// 19--ResumeReconcile
    /// </summary>
    public short Status { get; set; }

    /// <summary>
    /// Check-----------PurposeID/VendoriD/CustomerID/EmpID/OthersID,
    /// Bill Payment----VendorID,
    /// DCP-------------null,
    /// Franchise fee----Ref.Num,
    /// Loans-----------check no,
    /// Gas Bill----------check no,
    /// Receipts---------check no,
    /// Customer receipt-CustomerID,
    /// Fund transfer-----Entry no,
    /// Bill Entry---------VendorID, PurposeID,
    /// Invoice-----------invoice no,
    /// Wage cost--------wage cost name,
    /// Paychecks--------null,
    /// Adhoc payment---check no,
    /// Tax payment-------check no,
    /// Other payment----check no,
    /// Journal------------PurposeID,
    /// YearEndProcess---null
    /// 
    /// </summary>
    public byte[] SourceId { get; set; }

    /// <summary>
    /// TST-Transaction Source Type,
    /// JST- Journal Source Type--
    /// Check--------( TST -0,1,2,13,80),
    /// Bill Payment----( JST-21, TST - 1,84,85),
    /// DCP-------( TST -0,1,2,13,80),
    /// Franchise fee----( JST-13, TST -80),
    /// Loans-----------( TST -0,1,80),
    /// Receipts------(TST- 0,1,2,13,80,87),
    /// Customer receipt-(TST-0,22,85),
    /// Fund transfer-----( TST -0,1,2,13,80,JST-41,42),
    /// Bill Entry------(TST-1,80),
    /// Invoice-------(TST-0,80),
    /// Wage cost-----( JST-25,26,27,28,29,30,31),
    /// Paychecks--------(TST-2)(JST-30),
    /// Adhoc payment---(TST-3) (JST-17),
    /// Tax payment-------(TST-4) (JST-18),
    /// Other payment----(TST-4) (JST-19),
    /// Journal----------(TST-80,87),
    /// Sales-----------(TST- 0,5,6,7,11,15,16,17,18)(JST-66)
    /// 
    /// </summary>
    public short? SourceType { get; set; }

    public byte[] StoreId { get; set; }

    public byte[] FranchiseeId { get; set; }

    public byte[] CostcenterId { get; set; }

    public string XmlMemo { get; set; }

    public byte[] ReconciliationId { get; set; }

    public short? Order { get; set; }

    /// <summary>
    /// Enum-----Transaction status-
    /// Reconcilation-------6,
    /// ResumeReconcilation--19
    /// </summary>
    public byte? ReconStatus { get; set; }

    public short? TargetType { get; set; }

    public byte[] TargetId { get; set; }

    public byte[] ReferenceId { get; set; }

    public bool? Billable { get; set; }

    public bool? IsBilled { get; set; }

    public byte? IsBankTransactionRefId { get; set; }

    public string BankTransactionRefId { get; set; }

    public long Tid { get; set; }

    public string MerchantReconRefId { get; set; }

    public virtual ICollection<Transaction> InverseParent { get; set; } = new List<Transaction>();

    public virtual JournalEntry JournalEntry { get; set; }

    public virtual Transaction Parent { get; set; }

    public virtual Store Store { get; set; }
}