// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common.App.Contracts;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using WHSubscription.Domain.DataModel;
namespace WHSubscription.Infra.DBCon;

public partial class WHSubscriptionContext : DbContext, IAppDBContext
{
    public WHSubscriptionContext(DbContextOptions<WHSubscriptionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Whlog> Whlogs { get; set; }

    public virtual DbSet<Whsubscription> Whsubscriptions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Whlog>(entity =>
        {
            entity.ToTable("WHLog");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MessageId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("MessageID");
            entity.Property(e => e.Payload)
                .HasMaxLength(2500)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasComment("1-Success,2-ReAttemptSuccess,3-Fail,4-Discarded");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.Exception)
               .HasColumnName("Exception")
               .HasMaxLength(1000)
               .IsUnicode(false)
               .HasComment("Stores exception message if any during processing");

        });

        modelBuilder.Entity<Whsubscription>(entity =>
        {
            entity.ToTable("WHSubscription");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CallBackUrl)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.RefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("RefID");
            entity.Property(e => e.UrlName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("0-For All,other than 0 for specfic clients with comma seperated");
            entity.Property(e => e.EventType)
              .HasColumnName("EventType")
              .HasComment("Specifies the type of event this subscription listens to");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}