// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportsAndConfig.Domain.DataModel;

public partial class GroupConfigAccSetting
{
    public long Id { get; set; }

    public long GroupId { get; set; }

    public long? FromAccountNumber { get; set; }

    public long? ToAccountNumber { get; set; }

    public int? AccounType { get; set; }

    public short Status { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public byte[] ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual GroupConfig Group { get; set; }
}