// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedAccountMapping
{
    public long Id { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] CorpId { get; set; }

    public DateTime? LastSynchedOn { get; set; }

    public long? FormatId { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public long? LinkAccId { get; set; }

    public virtual ImportFormatSettings Format { get; set; }

    public virtual FeedAccount IdNavigation { get; set; }
}