// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedSettings
{
    public long Id { get; set; }

    public byte[] ClientId { get; set; }

    public bool? EnablePendingTrans { get; set; }

    public int? TransDateRange { get; set; }

    public bool? PosibleMatchBasedOn { get; set; }

    public bool? IncludeReconcileTransactions { get; set; }

    public bool? EnablePostFeedRule { get; set; }

    public bool? DsCashCheckEnable { get; set; }

    public short? Status { get; set; }
}