// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedInstitute
{
    public long Id { get; set; }

    public long? ProviderRegId { get; set; }

    public string InsOffName { get; set; }

    public string InsName { get; set; }

    public string InsProviderId { get; set; }

    public string ProviderAccessId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public short? Status { get; set; }

    public string ProviderStatus { get; set; }

    public string ServiceProvider { get; set; }
    public string DuplicateConnectionId { get; set; }    

    public virtual ICollection<FeedAccount> FeedAccount { get; set; } = new List<FeedAccount>();

    public virtual ICollection<ProviderInsChangeLog> ProviderInsChangeLog { get; set; } = new List<ProviderInsChangeLog>();

    public virtual ProviderRegister ProviderReg { get; set; }
}