// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BankFeed.Domain.DataModel;

public partial class FeedTransactions
{
    public long Id { get; set; }

    public long? FeedAccId { get; set; }

    public string TransProviderId { get; set; }

    public string TransType { get; set; }

    public string Description { get; set; }

    public string CheckNumber { get; set; }

    public string TransName { get; set; }

   // [Column(TypeName = "decimal(18,2)")]
    public decimal? Amount { get; set; }

    public DateTime? TransDate { get; set; }

    public long? FeedRuleId { get; set; }

    public bool? IsAutoRuleApplied { get; set; }

    public short? TransPostType { get; set; }

    public decimal? RunningBalance { get; set; }

    public int? PageNo { get; set; }

    public short? Status { get; set; }

    public string LogSeqId { get; set; }

    public virtual FeedAccount FeedAcc { get; set; }

    public virtual FeedRule FeedRule { get; set; }

    public virtual ICollection<FeedTransactionMapping> FeedTransactionMapping { get; set; } = new List<FeedTransactionMapping>();

    public virtual ICollection<FeedTransactionPossibleMatches> FeedTransactionPossibleMatches { get; set; } = new List<FeedTransactionPossibleMatches>();
}