// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedPossibleTransSharing
{
    public long Id { get; set; }

    public string ReqId { get; set; }

    public DateTime? TransDate { get; set; }

    public string CheckNo { get; set; }

    public string Description { get; set; }

    public string PayeeName { get; set; }

    public decimal? Amount { get; set; }

    public string TransactionTypeName { get; set; }

    public short? TransactionType { get; set; }

    public bool? IsDailySale { get; set; }

    public string TransId { get; set; }

    public string JournalEntryId { get; set; }

    public string BillNum { get; set; }

    public DateTime? BillDate { get; set; }

    public DateTime? DueDate { get; set; }

    public byte? DebitCredit { get; set; }

    public string AdjustmentLinkId { get; set; }

    public byte? IsAdjEntry { get; set; }

    public string MergRefId { get; set; }

    public string MergeLineId { get; set; }
}