// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedConnectionLog
{
    public long Id { get; set; }

    public long? FeedAccId { get; set; }

    public short? LogType { get; set; }

    public string LogDescription { get; set; }

    public DateTime? LoggedOn { get; set; }

    public long? TransCount { get; set; }

    public long? FormatId { get; set; }

    public string LogSeqId { get; set; }

    public short? Status { get; set; }

    public DateTime? EndDate { get; set; }

    public virtual FeedAccount FeedAcc { get; set; }
}