// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedBankOrCreditAccounts
{
    public long Id { get; set; }

    public long FeedRuleId { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] AccountId { get; set; }

    public bool? IsOppositeTransfer { get; set; }

    public virtual FeedRule FeedRule { get; set; }
}