// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedTransactionPossibleMatches
{
    public long Id { get; set; }

    public long? FeedTransId { get; set; }

    public byte[] JournalEntryId { get; set; }

    public byte[] TransactionId { get; set; }

    public short? Status { get; set; }

    public DateTime TransDate { get; set; }

    public string CheckNo { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public short? TransactionType { get; set; }

    public string TransactionTypeName { get; set; }

    public string PayeeName { get; set; }

    public string BillNum { get; set; }

    public DateTime? BillDate { get; set; }

    public DateTime? DueDate { get; set; }

    public bool? IsSelected { get; set; }

    public virtual FeedTransactions FeedTrans { get; set; }
}