// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedSynchSettings
{
    public long Id { get; set; }

    public byte[] ClientId { get; set; }

    public int? TimeZoneId { get; set; }

    public string SynchHour { get; set; }

    public short Status { get; set; }

    public DateTime? SynchTimeUtc { get; set; }

    public long? ClientInfoId { get; set; }

    public virtual FeedTimeZone TimeZone { get; set; }
}