// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedAccountMergeSettings
{
    public long Id { get; set; }

    public byte[] LineId { get; set; }

    public short? DeptType { get; set; }

    public byte? MergeType { get; set; }

    public long? FeedAccId { get; set; }

    public virtual FeedAccount FeedAcc { get; set; }
}