// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedRuleMapping
{
    public long Id { get; set; }

    public byte[] CorpId { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] NameId { get; set; }

    public short? NameType { get; set; }

    public short? ActTransType { get; set; }

    public byte[] PaymentMethodId { get; set; }

    public long? FeedRuleId { get; set; }

    public byte[] DepartmentId { get; set; }

    public byte[] PurposeId { get; set; }

    public bool? IsAmountOrPercentage { get; set; }

    public decimal? AmountOrPercentageVal { get; set; }

    public byte? Status { get; set; }

    public short? SplitLineNum { get; set; }

    public virtual FeedRule FeedRule { get; set; }
}