// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedRule
{
    public long Id { get; set; }

    public long? FeedAccId { get; set; }

    public byte[] BankOrCreditAccountId { get; set; }

    public byte[] CorporationId { get; set; }

    public string SetUpFor { get; set; }

    public string Memo { get; set; }

    public bool? AutoApplyEnable { get; set; }

    public short? FeedTransType { get; set; }

    public short? RulePriority { get; set; }

    public short? QueryMatchType { get; set; }

    public short? Status { get; set; }

    public bool? IsCloneEnable { get; set; }

    public short? RuleCategoryType { get; set; }

    public string RuleId { get; set; }

    public short? ActTransType { get; set; }

    public bool? IsBankOrCreditCard { get; set; }

    public bool? IsPostBill { get; set; }

    public virtual FeedAccount FeedAcc { get; set; }

    public virtual ICollection<FeedBankOrCreditAccounts> FeedBankOrCreditAccounts { get; set; } = new List<FeedBankOrCreditAccounts>();

    public virtual ICollection<FeedRuleDetails> FeedRuleDetails { get; set; } = new List<FeedRuleDetails>();

    public virtual ICollection<FeedRuleMapping> FeedRuleMapping { get; set; } = new List<FeedRuleMapping>();

    public virtual ICollection<FeedTransactions> FeedTransactions { get; set; } = new List<FeedTransactions>();

    public virtual ICollection<FeedTransactionsDeleted> FeedTransactionsDeleted { get; set; } = new List<FeedTransactionsDeleted>();
}