// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class FeedTimeZone
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public DateTime? CreatedOn { get; set; }

    public short? Status { get; set; }

    public bool? IsDefault { get; set; }

    public virtual ICollection<FeedSynchSettings> FeedSynchSettings { get; set; } = new List<FeedSynchSettings>();
}