// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankFeed.Domain.DataModel;

public partial class ImportFormatSettings
{
    public long Id { get; set; }

    public long? ProviderRegId { get; set; }

    public string FormatName { get; set; }

    public int? ColumnCount { get; set; }

    public string TemplatePath { get; set; }

    public string Date { get; set; }

    public string Memo { get; set; }

    public string Num { get; set; }

    public int? DataReadfrom { get; set; }

    public short? AmountType { get; set; }

    public short? AmountMode { get; set; }

    public string AmountColumn1 { get; set; }

    public string AmountColumn2 { get; set; }

    public short? Status { get; set; }

    public short? IsHeader { get; set; }

    public byte[] ClientId { get; set; }

    public byte[] FormatRefId { get; set; }

    public virtual ICollection<FeedAccountMapping> FeedAccountMapping { get; set; } = new List<FeedAccountMapping>();
}