// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.AuthDataModel;

public partial class UserLoginActivity
{
    public long Id { get; set; }

    public long UserInfoId { get; set; }

    public string Token { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public long? ClientInfoId { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string AuthId { get; set; }

    public string ClientUrl { get; set; }

    public virtual ClientInfo ClientInfo { get; set; }
}