// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Dashboard.Domain.DataModel;
using Common.App.Contracts;

namespace Dashboard.Infra.DBCon;

public partial class DashboardCustomizationContext : DbContext, IAppDBContext
{
    public DashboardCustomizationContext(DbContextOptions<DashboardCustomizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<WidgetCustomization> WidgetCustomization { get; set; }

    public virtual DbSet<WidgetFormula> WidgetFormula { get; set; }

    public virtual DbSet<WidgetFormulaDetails> WidgetFormulaDetails { get; set; }

    public virtual DbSet<WidgetFormulaSettings> WidgetFormulaSettings { get; set; }

    public virtual DbSet<WidgetPrivilegeDetails> WidgetPrivilegeDetails { get; set; }

    public virtual DbSet<WidgetPrivileges> WidgetPrivileges { get; set; }

    public virtual DbSet<WidgetUserSettings> WidgetUserSettings { get; set; }

    public virtual DbSet<Widgets> Widgets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WidgetCustomization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetCu__3214EC273C6E4147");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.IncomeDeptId).HasColumnName("IncomeDeptID");
            entity.Property(e => e.IncomeGroupId).HasColumnName("IncomeGroupID");
            entity.Property(e => e.PayrollDeptId).HasColumnName("PayrollDeptID");
        });

        modelBuilder.Entity<WidgetFormula>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetFo__3214EC2715F20103");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ActualFormula)
                .IsRequired()
                .HasColumnType("text");
            entity.Property(e => e.DisplayFormula)
                .IsRequired()
                .HasColumnType("text");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WidgetFormulaDetails>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CustomBinId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CustomBinID");
            entity.Property(e => e.CustomKeyId).HasColumnName("CustomKeyID");
            entity.Property(e => e.CustomKeyName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FormulaId).HasColumnName("FormulaID");

            entity.HasOne(d => d.Formula).WithMany(p => p.WidgetFormulaDetails)
                .HasForeignKey(d => d.FormulaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WidgetFormulaDetails_WidgetFormula");
        });

        modelBuilder.Entity<WidgetFormulaSettings>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetFo__3214EC275D3A7C94");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.FormulaId).HasColumnName("FormulaID");
            entity.Property(e => e.SourceName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.WidgetId).HasColumnName("WidgetID");

            entity.HasOne(d => d.Formula).WithMany(p => p.WidgetFormulaSettings)
                .HasForeignKey(d => d.FormulaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WidgetFormulaSettings_WidgetFormula");

            entity.HasOne(d => d.Widget).WithMany(p => p.WidgetFormulaSettings)
                .HasForeignKey(d => d.WidgetId)
                .HasConstraintName("FK_WidgetFormulaSettings_Widgets");
        });

        modelBuilder.Entity<WidgetPrivilegeDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetPr__3214EC278DEE417A");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.WidgetId).HasColumnName("WidgetID");
            entity.Property(e => e.WidgetPrivId).HasColumnName("WidgetPrivID");

            entity.HasOne(d => d.Widget).WithMany(p => p.WidgetPrivilegeDetails)
                .HasForeignKey(d => d.WidgetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WidgetPri__Widge__2A164134");

            entity.HasOne(d => d.WidgetPriv).WithMany(p => p.WidgetPrivilegeDetails)
                .HasForeignKey(d => d.WidgetPrivId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WidgetPri__Widge__29221CFB");
        });

        modelBuilder.Entity<WidgetPrivileges>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetPr__3214EC27CD246B0E");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.IsAddWidget).HasDefaultValue(false);
            entity.Property(e => e.IsExport).HasDefaultValue(false);
            entity.Property(e => e.IsSchedule).HasDefaultValue(false);
            entity.Property(e => e.SourceId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");
            entity.Property(e => e.UrlInfoId).HasColumnName("UrlInfoID");
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");
        });

        modelBuilder.Entity<WidgetUserSettings>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WidgetUs__3214EC27B69E4487");

            entity.HasIndex(e => new { e.WidgetId, e.UserId }, "CK_Unique_WidgetID_UserID").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ColumnValue)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CompValue)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.WidgetId).HasColumnName("WidgetID");

            entity.HasOne(d => d.Widget).WithMany(p => p.WidgetUserSettings)
                .HasForeignKey(d => d.WidgetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WidgetUserSettings_Widgets");
        });

        modelBuilder.Entity<Widgets>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Widgets__3214EC27AB365B34");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.DefaultComparisionType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DefaultDateViewType).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DefaultFilterType).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DisplayWidth).HasDefaultValue((short)12);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}