// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using UserMgmt.Domain.DataModel;
namespace UserMgmt.Infra.DBCon;

public partial class UMDBContext : DbContext
{
    public UMDBContext(DbContextOptions<UMDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClientInfo> ClientInfo { get; set; }

    public virtual DbSet<MenuInformation> MenuInformation { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<RolePrevileges> RolePrevileges { get; set; }

    public virtual DbSet<ServerInfo> ServerInfo { get; set; }

    public virtual DbSet<Urlinfo> Urlinfo { get; set; }

    public virtual DbSet<UrlserverInfo> UrlserverInfo { get; set; }

    public virtual DbSet<UserClientLink> UserClientLink { get; set; }

    public virtual DbSet<UserCorpLink> UserCorpLink { get; set; }

    public virtual DbSet<UserCredentials> UserCredentials { get; set; }

    public virtual DbSet<UserInfo> UserInfo { get; set; }

    public virtual DbSet<UserLoginActivity> UserLoginActivity { get; set; }

    public virtual DbSet<UserPclink> UserPclink { get; set; }

    public virtual DbSet<UserPrevileges> UserPrevileges { get; set; }
    public virtual DbSet<DumpUserInformation> DumpUserInfo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClientInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("ClientID");
            entity.Property(e => e.ClientSecret)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.UrlinfoId).HasColumnName("URLInfoID");
            entity.Property(e => e.UserId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");

            entity.HasOne(d => d.Urlinfo).WithMany(p => p.ClientInfo)
                .HasForeignKey(d => d.UrlinfoId)
                .HasConstraintName("FK_ClientInfo_UrlInfo");

            entity.HasOne(d => d.UserInfo).WithMany(p => p.ClientInfo)
                .HasForeignKey(d => d.UserInfoId)
                .HasConstraintName("FK_ClientInfo_UserInfo1");
        });

        modelBuilder.Entity<MenuInformation>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.HelpUrl)
                .HasMaxLength(500)
                .HasColumnName("HelpURL");
            entity.Property(e => e.IsDefault).HasComment("It will be set when it is loaded by default in child menus based parent menu (parentid)");
            entity.Property(e => e.MenuBinId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("MenuBinID");
            entity.Property(e => e.MenuLevel).HasComment("Level of the menu");
            entity.Property(e => e.MenuName)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MenuOrder).HasComment("It will decide oder");
            entity.Property(e => e.MenuType).HasComment("0-Workflow Menu,1-Admin Menus,2-DashBoard Menus,3-Related to dynamicMenu");
            entity.Property(e => e.NavUrl).HasMaxLength(500);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.Status).HasComment("0-InActive,1-Active,3-Deleted");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_MenuInformation_MenuInformation");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");

            entity.HasOne(d => d.Client).WithMany(p => p.Role)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK_Role_ClientInfo");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Role_Role");
        });

        modelBuilder.Entity<RolePrevileges>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MenuId).HasColumnName("MenuID");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");

            entity.HasOne(d => d.GivenByNavigation).WithMany(p => p.RolePrevileges)
                .HasForeignKey(d => d.GivenBy)
                .HasConstraintName("FK_RolePrevileges_UserClientLink");

            entity.HasOne(d => d.Menu).WithMany(p => p.RolePrevileges)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("FK_RolePrevileges_MenuInformation");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePrevileges)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserPrevileges_Role");
        });

        modelBuilder.Entity<ServerInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Credentials)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ServerIp)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("ServerIP");
        });

        modelBuilder.Entity<Urlinfo>(entity =>
        {
            entity.ToTable("URLInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Url)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("URL");
        });

        modelBuilder.Entity<UrlserverInfo>(entity =>
        {
            entity.ToTable("URLServerInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DbserverId).HasColumnName("DBServerID");
            entity.Property(e => e.DomianServerId).HasColumnName("DomianServerID");
            entity.Property(e => e.ReportServerId).HasColumnName("ReportServerID");
            entity.Property(e => e.Urlid).HasColumnName("URLID");

            entity.HasOne(d => d.Url).WithMany(p => p.UrlserverInfo)
                .HasForeignKey(d => d.Urlid)
                .HasConstraintName("FK_URLServerInfo_URLInfo");
        });

        modelBuilder.Entity<UserClientLink>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UserId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");

            entity.HasOne(d => d.ClientInfo).WithMany(p => p.UserClientLink)
                .HasForeignKey(d => d.ClientInfoId)
                .HasConstraintName("FK_UserClinetLink_ClientInfo");

            entity.HasOne(d => d.Role).WithMany(p => p.UserClientLink)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserClientLink_Role");

            entity.HasOne(d => d.UserInfo).WithMany(p => p.UserClientLink)
                .HasForeignKey(d => d.UserInfoId)
                .HasConstraintName("FK_UserClinetLink_UserInfo");
        });

        modelBuilder.Entity<UserCorpLink>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorpId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorpID");
            entity.Property(e => e.UserLinkId).HasColumnName("UserLinkID");

            entity.HasOne(d => d.UserLink).WithMany(p => p.UserCorpLink)
                .HasForeignKey(d => d.UserLinkId)
                .HasConstraintName("FK_UserCorpLink_UserClientLink");
        });

        modelBuilder.Entity<UserCredentials>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Password)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.UserCredentials)
                .HasForeignKey<UserCredentials>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCredentials_UserInfo");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FirstName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.MiddleName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.UserName)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserLoginActivity>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AuthId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("AuthID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.ClientUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.ExpiryDate).HasPrecision(0);
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.Token)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");

            entity.HasOne(d => d.ClientInfo).WithMany(p => p.UserLoginActivity)
                .HasForeignKey(d => d.ClientInfoId)
                .HasConstraintName("FK_UserLoginActivity_ClientInfo");

            entity.HasOne(d => d.UserInfo).WithMany(p => p.UserLoginActivity)
                .HasForeignKey(d => d.UserInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserLoginActivity_UserInfo");
        });

        modelBuilder.Entity<UserPclink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UserPcLink");

            entity.ToTable("UserPCLink");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.UserCorpLinkId).HasColumnName("UserCorpLinkID");

            entity.HasOne(d => d.UserCorpLink).WithMany(p => p.UserPclink)
                .HasForeignKey(d => d.UserCorpLinkId)
                .HasConstraintName("FK_UserPcLink_UserCorpLink");
        });

        modelBuilder.Entity<UserPrevileges>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MenuId).HasColumnName("MenuID");
            entity.Property(e => e.UserLinkId).HasColumnName("UserLinkID");

            entity.HasOne(d => d.GivenByNavigation).WithMany(p => p.UserPrevilegesGivenByNavigation)
                .HasForeignKey(d => d.GivenBy)
                .HasConstraintName("FK_UserPrevileges_UserClientLink1");

            entity.HasOne(d => d.Menu).WithMany(p => p.UserPrevileges)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("FK_UserPrevileges_MenuInformation");

            entity.HasOne(d => d.UserLink).WithMany(p => p.UserPrevilegesUserLink)
                .HasForeignKey(d => d.UserLinkId)
                .HasConstraintName("FK_UserPrevileges_UserClientLink");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}