// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimBrand
{
    public int BrandKey { get; set; }

    public string BrandName { get; set; }

    public byte HotelChain { get; set; }

    public DateTime? LoadedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public short Status { get; set; }
}