// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimClient
{
    public long ClientKey { get; set; }

    public byte[] ClientId { get; set; }

    public string LoadedBy { get; set; }

    public DateTime? LoadedDate { get; set; }

    public long Urlkey { get; set; }
}