// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimDailySalesDepartment
{
    public long DailySaleDeptKey { get; set; }

    public string Name { get; set; }

    public short DeptType { get; set; }

    public short? Status { get; set; }

    public string LoadedBy { get; set; }

    public DateTime? LoadedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public byte[] DailysaleDeptId { get; set; }

    public long? Urlkey { get; set; }
}