// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimDailySaleLinesStaging
{
    public long Id { get; set; }

    public byte[] LineId { get; set; }

    public string Name { get; set; }

    public short? Status { get; set; }

    public byte[] CorporationId { get; set; }

    public short? IsRoomsSold { get; set; }

    public short? IsRoomsAvailable { get; set; }

    public short? IsVacant { get; set; }

    public short? IsOutOfOrder { get; set; }

    public short? IsComp { get; set; }

    public short? IsAvgCnt { get; set; }

    public short? RoomType { get; set; }

    public short? EnableAdroravg { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] Pcid { get; set; }

    public short? ArledgerType { get; set; }

    public short? AdjustLedgerType { get; set; }

    public short? IsGuestLedger { get; set; }

    public short? IsOtherLedger { get; set; }

    public byte[] DepartmentId { get; set; }

    public short? DeptType { get; set; }

    public short? CardTypeOrder { get; set; }

    public short? CardDeptType { get; set; }

    public string CardTypeName { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int? LoadStatus { get; set; }
    public long LineOrder {  get; set; }
    public byte[] GroupID { get; set; }
}