// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimIncConfigurationStaging
{
    public long Id { get; set; }

    public byte[] CorporationId { get; set; }

    public long? SubDeptId { get; set; }

    public long? GroupId { get; set; }

    public byte? Type { get; set; }

    public byte? Order { get; set; }

    public long IncConfigDetailId { get; set; }

    public byte[] AccountId { get; set; }

    public short? DetailOrder { get; set; }

    public short? PayrollItemType { get; set; }

    public short? HoursType { get; set; }

    public byte? Status { get; set; }

    public long IncConfigId { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int? LoadStatus { get; set; }
}