// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimIncGroupStaging
{
    public long Id { get; set; }

    public string Name { get; set; }

    public byte[] CorporationId { get; set; }

    public long GroupId { get; set; }

    public long? GroupId1 { get; set; }

    public long? GroupId2 { get; set; }

    public short? Status { get; set; }

    public string LoadedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int? LoadStatus { get; set; }
}