// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class DimOthersStaging
{
    public long Id { get; set; }

    public byte[] OtherId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public short? Status { get; set; }

    public byte[] CorporationId { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int? LoadStatus { get; set; }
}