// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class F5
{
    public decimal? F1 { get; set; }
}