// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactDailySalesArstaging
{
    public long Id { get; set; }

    public byte[] LineId { get; set; }

    public byte[] DailyConfigInputId { get; set; }

    public short? SourceType { get; set; }

    public decimal? Amount { get; set; }

    public byte[] CaccountId { get; set; }

    public byte[] DaccountId { get; set; }

    public byte[] DarecId { get; set; }

    public decimal? DetAmount { get; set; }

    public byte[] DetId { get; set; }

    public byte[] AccountId { get; set; }

    public string Description { get; set; }

    public long? DetOrder { get; set; }

    public short? DetStatus { get; set; }

    public short? Drstatus { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] Pcid { get; set; }

    public DateTime? SaleDate { get; set; }

    public byte[] DetSourceId { get; set; }

    public short? DetSourceType { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int? LoadStatus { get; set; }
}