// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[Table("FactAdjustmentsStaging")]
public partial class FactAdjustmentsStaging
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [Column("BillAdjustmentID")]
    [MaxLength(18)]
    public byte[] BillAdjustmentId { get; set; }

    [Required]
    [Column("BillID")]
    [MaxLength(18)]
    public byte[] BillId { get; set; }

    [Required]
    [Column("MemoID")]
    [MaxLength(18)]
    public byte[] MemoId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Precision(0)]
    public DateTime AdjustmentDate { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Column("URLKey")]
    public long Urlkey { get; set; }

    [Precision(0)]
    public DateTime? UpdatedDate { get; set; }

    [Column("BillPaymentID")]
    [MaxLength(18)]
    public byte[] BillPaymentId { get; set; }

    [Precision(0)]
    public DateTime? LoadTimeStamp { get; set; }

    public int LoadStatus { get; set; }
}