// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[PrimaryKey("BudgetTransId", "PartitionKey")]
[Table("Fact_Budget_Historical")]
public partial class FactBudgetHistorical
{
    [Key]
    [Column("BudgetTransID")]
    public long BudgetTransId { get; set; }

    public long DateKey { get; set; }

    public long? AccountKey { get; set; }

    public long? LineKey { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "decimal(18, 5)")]
    public decimal? Stats { get; set; }

    public long CorpKey { get; set; }

    [Column("PCKey")]
    public long? Pckey { get; set; }

    [Required]
    [Column("BudgetID")]
    [MaxLength(18)]
    public byte[] BudgetId { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string LoadedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LoadedDate { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    public short? Status { get; set; }

    [Column("URLKey")]
    public long Urlkey { get; set; }

    [Key]
    public long PartitionKey { get; set; }
}