// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactDailySalesAr
{
    public long Darkey { get; set; }

    public long? LineKey { get; set; }

    public byte[] DailyConfigInputId { get; set; }

    public short? SourceType { get; set; }

    public decimal? Amount { get; set; }

    public long? CaccountKey { get; set; }

    public long? DaccountKey { get; set; }

    public byte[] DarecId { get; set; }

    public decimal? DetAmount { get; set; }

    public byte[] DetId { get; set; }

    public long? AccountKey { get; set; }

    public string Description { get; set; }

    public long? DetOrder { get; set; }

    public short? DetStatus { get; set; }

    public short? Drstatus { get; set; }

    public long? Urlkey { get; set; }

    public byte[] DetSourceId { get; set; }

    public short? DetSourceType { get; set; }

    public long? CorpKey { get; set; }

    public long? Pckey { get; set; }

    public DateTime? SaleDate { get; set; }

    public long PartitionKey { get; set; }
}