// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactAccrualInactive
{
    public long TransId { get; set; }

    public long? DateKey { get; set; }

    public long? Pckey { get; set; }

    public long AccountKey { get; set; }

    public long? CustomerKey { get; set; }

    public long? VendorKey { get; set; }

    public long? EmpKey { get; set; }

    public long? OtherKey { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Stats { get; set; }

    public long CorpKey { get; set; }

    public bool IsReconciled { get; set; }

    public byte[] TransactionId { get; set; }

    public byte[] JournalEntryId { get; set; }

    public string LoadedBy { get; set; }

    public DateTime? LoadedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Status { get; set; }

    public bool? DebitCredit { get; set; }

    public short? SourceType { get; set; }

    public short? ParentSourceType { get; set; }

    public long Urlkey { get; set; }

    public short Tstatus { get; set; }

    public byte[] SourceId { get; set; }

    public byte[] TargetId { get; set; }

    public short? TargetType { get; set; }

    public short? TsourceType { get; set; }

    public DateTime? VoidDate { get; set; }

    public DateTime? ReconcileDate { get; set; }

    public DateTime? BillDate { get; set; }

    public DateTime? DueDate { get; set; }

    public byte[] ReconciliationId { get; set; }

    public DateTime? ClearedDate { get; set; }

    public int? TransNumber { get; set; }

    public string EntryNumber { get; set; }

    public byte[] CreatedBy { get; set; }

    public byte[] ModifiedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Memo { get; set; }

    public string ReferenceNumber { get; set; }

    public byte[] ParentId { get; set; }

    public byte[] PurPoseId { get; set; }

    public string PurposeName { get; set; }

    public byte[] JesourceId { get; set; }

    public long PartitionKey { get; set; }
}