// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[Table("FactBillPaymentStaging")]
public partial class FactBillPaymentStaging
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("BillPayInformationID")]
    public long? BillPayInformationId { get; set; }

    [Precision(0)]
    public DateTime? PaidDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PaidAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PaidNumber { get; set; }

    [StringLength(900)]
    [Unicode(false)]
    public string PaidMemo { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    [Column("PaidTransactionID")]
    [MaxLength(18)]
    public byte[] PaidTransactionId { get; set; }

    [Column("PaidJournalEntryID")]
    [MaxLength(18)]
    public byte[] PaidJournalEntryId { get; set; }

    public short? PaidReconStatus { get; set; }

    [Column("ReconciliationID")]
    [MaxLength(18)]
    public byte[] ReconciliationId { get; set; }

    [Precision(0)]
    public DateTime? ReconcileDate { get; set; }

    public short? PaidStatus { get; set; }

    [Column("BillInformationID")]
    public long? BillInformationId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AppliedAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DiscountAmount { get; set; }

    [Column("DiscountTransactionID")]
    [MaxLength(18)]
    public byte[] DiscountTransactionId { get; set; }

    [Column("AppliedTransactionID")]
    [MaxLength(18)]
    public byte[] AppliedTransactionId { get; set; }

    [Column("BillEntryPayID")]
    public long? BillEntryPayId { get; set; }

    public short? BillEntryPayStatus { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    public long UrlKey { get; set; }

    [Column("PaymethodID")]
    [MaxLength(18)]
    public byte[] PaymethodId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymethodName { get; set; }

    public short? PaymthodType { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CheckNo { get; set; }

    [Column("AccountID")]
    [MaxLength(18)]
    public byte[] AccountId { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CreatedByName { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ModifiedByName { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [Precision(0)]
    public DateTime? LoadTimeStamp { get; set; }

    public int LoadStatus { get; set; }
}