// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactAccrualStaging
{
    public long Id { get; set; }

    public DateTime? EntryDate { get; set; }

    public byte[] StoreiD { get; set; }

    public byte[] AccountId { get; set; }

    public byte[] CustomerId { get; set; }

    public byte[] VendorId { get; set; }

    public byte[] EmployeeId { get; set; }

    public byte[] OtherId { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Stats { get; set; }

    public byte[] CorporationId { get; set; }

    public bool? IsReconciled { get; set; }

    public byte[] TransactionId { get; set; }

    public byte[] JournalEntryId { get; set; }

    public DateTime? ReconcileDate { get; set; }

    public short? Status { get; set; }

    public bool? DebitCredit { get; set; }

    public short? SourceType { get; set; }

    public short? ParentSourceType { get; set; }

    public short? Tstatus { get; set; }

    public byte[] TsourceId { get; set; }

    public byte[] TargetId { get; set; }

    public short? TargetType { get; set; }

    public short? TsourceType { get; set; }

    public DateTime? VoidDate { get; set; }

    public byte[] JsourceId { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime? BillDate { get; set; }

    public byte[] ReconciliationId { get; set; }

    public long Urlkey { get; set; }

    public DateTime? LoadTimeStamp { get; set; }

    public int LoadStatus { get; set; }

    public bool? IsBill { get; set; }
}