// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactPayroll
{
    public long PayrollKey { get; set; }

    public long EmpKey { get; set; }

    public long? PayrollDeptKey { get; set; }

    public long CorpKey { get; set; }

    public long? Pckey { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Stats { get; set; }

    public byte[] PayrollId { get; set; }

    public byte[] PayrollEmpId { get; set; }

    public long? DateKey { get; set; }

    public string LoadedBy { get; set; }

    public DateTime? LoadedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public byte? Status { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public byte[] ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public long Urlkey { get; set; }
}