// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[PrimaryKey("BillKey", "PartitionKey")]
[Table("Fact_Bills")]
public partial class FactBill
{
    [Key]
    public long BillKey { get; set; }

    [Column("BillInformationID")]
    public long BillInformationId { get; set; }

    [Required]
    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Outstanding { get; set; }

    public long? VendorKey { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    public short? DebitCredit { get; set; }

    public short? Status { get; set; }

    [Required]
    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    public long? TransKey { get; set; }

    [Precision(0)]
    public DateTime? EntryDate { get; set; }

    public long? EntryDateKey { get; set; }

    public short? SourceType { get; set; }

    [Column("PCKey")]
    public long? Pckey { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    [Column("ContractID")]
    [MaxLength(18)]
    public byte[] ContractId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EntryNumber { get; set; }

    [Precision(0)]
    public DateTime? BillDate { get; set; }

    public long CorpKey { get; set; }

    [Required]
    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CreatedByName { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ModifiedByName { get; set; }

    [Precision(0)]
    public DateTime? DueDate { get; set; }

    public long? DueDateKey { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccountNumber { get; set; }

    public long? UrlKey { get; set; }

    public long? VendorAccKey { get; set; }

    [Column("PaymethodID")]
    [MaxLength(18)]
    public byte[] PaymethodId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymethodName { get; set; }

    public short? PaymthodType { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Memo { get; set; }

    public bool? IsAttachment { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    [Key]
    public long PartitionKey { get; set; }
}