// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[Table("FactBillStaging")]
public partial class FactBillStaging
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("BillInformationID")]
    public long? BillInformationId { get; set; }

    [Column("JournalEntryID")]
    [MaxLength(18)]
    public byte[] JournalEntryId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Outstanding { get; set; }

    [Column("VendorID")]
    [MaxLength(18)]
    public byte[] VendorId { get; set; }

    public short? DebitCredit { get; set; }

    public short? Status { get; set; }

    [Column("TransactionID")]
    [MaxLength(18)]
    public byte[] TransactionId { get; set; }

    [Precision(0)]
    public DateTime? EntryDate { get; set; }

    public short? SourceType { get; set; }

    [Column("PCID")]
    [MaxLength(18)]
    public byte[] Pcid { get; set; }

    [Column("ContractID")]
    [MaxLength(18)]
    public byte[] ContractId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EntryNumber { get; set; }

    [Precision(0)]
    public DateTime? BillDate { get; set; }

    [Column("CorporationID")]
    [MaxLength(18)]
    public byte[] CorporationId { get; set; }

    [MaxLength(18)]
    public byte[] CreatedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CreatedByName { get; set; }

    [MaxLength(18)]
    public byte[] ModifiedBy { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ModifiedByName { get; set; }

    [Precision(0)]
    public DateTime? DueDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccountNumber { get; set; }

    [Column("AccountID")]
    public long? AccountId { get; set; }

    [Column("PaymethodID")]
    [MaxLength(18)]
    public byte[] PaymethodId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymethodName { get; set; }

    public short? PaymthodType { get; set; }

    [Column("MEMO")]
    [StringLength(800)]
    [Unicode(false)]
    public string Memo { get; set; }

    public long UrlKey { get; set; }

    [Precision(0)]
    public DateTime? LoadTimeStamp { get; set; }

    public bool? IsAttachment { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }

    [Precision(0)]
    public DateTime? ModifiedDate { get; set; }

    public int LoadStatus { get; set; }
}