// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WareHouseSynch.Domain.DataModel;

[Table("Fact_Adjustments")]
public partial class FactAdjustment
{
    [Key]
    public long AdjustmentKey { get; set; }

    [Required]
    [Column("BillAdjustmentID")]
    [MaxLength(18)]
    public byte[] BillAdjustmentId { get; set; }

    [Required]
    [Column("BillID")]
    [MaxLength(18)]
    public byte[] BillId { get; set; }

    [Required]
    [Column("MemoID")]
    [MaxLength(18)]
    public byte[] MemoId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Precision(0)]
    public DateTime AdjustmentDate { get; set; }

    public long CorpKey { get; set; }

    [Column("URLKey")]
    public long Urlkey { get; set; }

    [Precision(0)]
    public DateTime LoadedDate { get; set; }

    [Precision(0)]
    public DateTime? UpdatedDate { get; set; }

    [Column("BillPaymentID")]
    [MaxLength(18)]
    public byte[] BillPaymentId { get; set; }

    public short? Status { get; set; }
}