// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class FactBillsHistorical
{
    public long BillKey { get; set; }

    public long BillInformationId { get; set; }

    public byte[] JournalEntryId { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Outstanding { get; set; }

    public long? VendorKey { get; set; }

    public byte[] VendorId { get; set; }

    public short? DebitCredit { get; set; }

    public short? Status { get; set; }

    public byte[] TransactionId { get; set; }

    public long? TransKey { get; set; }

    public DateTime? EntryDate { get; set; }

    public long? EntryDateKey { get; set; }

    public short? SourceType { get; set; }

    public long? Pckey { get; set; }

    public byte[] Pcid { get; set; }

    public byte[] ContractId { get; set; }

    public string EntryNumber { get; set; }

    public DateTime? BillDate { get; set; }

    public long CorpKey { get; set; }

    public byte[] CorporationId { get; set; }

    public byte[] CreatedBy { get; set; }

    public string CreatedByName { get; set; }

    public byte[] ModifiedBy { get; set; }

    public string ModifiedByName { get; set; }

    public DateTime? DueDate { get; set; }

    public long? DueDateKey { get; set; }

    public string AccountNumber { get; set; }

    public long? UrlKey { get; set; }

    public long? VendorAccKey { get; set; }

    public byte[] PaymethodId { get; set; }

    public string PaymethodName { get; set; }

    public short? PaymthodType { get; set; }

    public string Memo { get; set; }

    public bool? IsAttachment { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public long PartitionKey { get; set; }
}