// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WareHouseSynch.Domain.DataModel;

public partial class SynchNotifier
{
    public long Id { get; set; }

    public short? ProcessType { get; set; }

    public DateTime? StartTime { get; set; }

    public bool? Status { get; set; }
}