// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dashboard.Analytics.Domain.DataModel;

public partial class ReqCustomFormula
{
    public long Id { get; set; }

    public string ReqId { get; set; }

    public byte[] CorporationId { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public byte? Type { get; set; }

    public byte? SubType { get; set; }

    public long? CustomKey { get; set; }

    public byte[] CustomBinId { get; set; }

    public string CustomKeyName { get; set; }

    public long? WidgetId { get; set; }

    public int? Corpkey { get; set; }

    public int? DeptId { get; set; }
}