// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Common.Domain.AuthDataModel;
namespace Common.Infra.AuthDBCon;

public partial class AuthDBContext : DbContext
{
    public AuthDBContext(DbContextOptions<AuthDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClientInfo> ClientInfo { get; set; }

    public virtual DbSet<UserLoginActivity> UserLoginActivity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClientInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("ClientID");
            entity.Property(e => e.ClientSecret)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.UrlinfoId).HasColumnName("URLInfoID");
            entity.Property(e => e.UserId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");
        });

        modelBuilder.Entity<UserLoginActivity>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AuthId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("AuthID");
            entity.Property(e => e.ClientInfoId).HasColumnName("ClientInfoID");
            entity.Property(e => e.ClientUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.ExpiryDate).HasPrecision(0);
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.Token)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.UserInfoId).HasColumnName("UserInfoID");

            entity.HasOne(d => d.ClientInfo).WithMany(p => p.UserLoginActivity)
                .HasForeignKey(d => d.ClientInfoId)
                .HasConstraintName("FK_UserLoginActivity_ClientInfo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}