// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WHSubscription.Domain.DataModel;

public partial class Whsubscription
{
    public long Id { get; set; }

    public byte[] RefId { get; set; }

    public string Name { get; set; }

    public string CallBackUrl { get; set; }

    /// <summary>
    /// 0-For All,other than 0 for specfic clients with comma seperated
    /// </summary>
    public string? UrlName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public short? Status { get; set; }
    public int? EventType { get; set; }
}