// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common.App.Contracts;
using DailySales.Domain.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
namespace DailySales.Infra.DBCon;

public partial class DailySalesContext : DbContext,IAppDBContext
{
    public DailySalesContext(DbContextOptions<DailySalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdjustOpeningBalance> AdjustOpeningBalance { get; set; }

    public virtual DbSet<ApprovalComments> ApprovalComments { get; set; }

    public virtual DbSet<ApprovalPloicy> ApprovalPloicy { get; set; }

    public virtual DbSet<ApprovalPloicyDetails> ApprovalPloicyDetails { get; set; }

    public virtual DbSet<DailyConfigDepartment> DailyConfigDepartment { get; set; }

    public virtual DbSet<DailyConfigGroup> DailyConfigGroup { get; set; }

    public virtual DbSet<DailyConfigInputEntry> DailyConfigInputEntry { get; set; }

    public virtual DbSet<DailyConfigInputEntryAr> DailyConfigInputEntryAr { get; set; }

    public virtual DbSet<DailyConfigInputEntryArdetails> DailyConfigInputEntryArdetails { get; set; }

    public virtual DbSet<DailyConfigInputEntryReceipt> DailyConfigInputEntryReceipt { get; set; }

    public virtual DbSet<DailyConfigInputEntryReceiptDetails> DailyConfigInputEntryReceiptDetails { get; set; }

    public virtual DbSet<DailyConfigInputEntryRevenue> DailyConfigInputEntryRevenue { get; set; }

    public virtual DbSet<DailyConfigInputEntryRevenueDetails> DailyConfigInputEntryRevenueDetails { get; set; }

    public virtual DbSet<DailyConfigInputEntryStatistics> DailyConfigInputEntryStatistics { get; set; }

    public virtual DbSet<DailyConfigInputEntryStatisticsDetails> DailyConfigInputEntryStatisticsDetails { get; set; }

    public virtual DbSet<DailyConfigLine> DailyConfigLine { get; set; }

    public virtual DbSet<DailyConfigVerification> DailyConfigVerification { get; set; }

    public virtual DbSet<DailySaleDefaults> DailySaleDefaults { get; set; }

    public virtual DbSet<DsCashCheckFilterReq> DsCashCheckFilterReq { get; set; }

    public virtual DbSet<DsdepositInfo> DsdepositInfo { get; set; }

    public virtual DbSet<DsdepositInfoDetails> DsdepositInfoDetails { get; set; }

    public virtual DbSet<Dsdeposits> Dsdeposits { get; set; }

    public virtual DbSet<DummyDailyConfigInputEntry> DummyDailyConfigInputEntry { get; set; }

    public virtual DbSet<DummyDailyConfigInputEntryArreceipt> DummyDailyConfigInputEntryArreceipt { get; set; }

    public virtual DbSet<DummyDailyConfigInputEntryRevStat> DummyDailyConfigInputEntryRevStat { get; set; }

    public virtual DbSet<DummyPmscorpMappingDetails> DummyPmscorpMappingDetails { get; set; }

    public virtual DbSet<JournalEntry> JournalEntry { get; set; }

    public virtual DbSet<JournalEntryExt> JournalEntryExt { get; set; }

    public virtual DbSet<Locking> Locking { get; set; }

    public virtual DbSet<Lookup> Lookup { get; set; }

    public virtual DbSet<MerchantCoapreference> MerchantCoapreference { get; set; }

    public virtual DbSet<OtbforeCastDetails> OtbforeCastDetails { get; set; }

    public virtual DbSet<OtbforeCastIndividualDetails> OtbforeCastIndividualDetails { get; set; }

    public virtual DbSet<OtbforeCastInfo> OtbforeCastInfo { get; set; }

    public virtual DbSet<PmsclientInfo> PmsclientInfo { get; set; }

    public virtual DbSet<PmscorporationMappindDetails> PmscorporationMappindDetails { get; set; }

    public virtual DbSet<PmscorporationMapping> PmscorporationMapping { get; set; }

    public virtual DbSet<PmsfacilityMap> PmsfacilityMap { get; set; }

    public virtual DbSet<PmsfacilityMapDetails> PmsfacilityMapDetails { get; set; }

    public virtual DbSet<Pmsinfo> Pmsinfo { get; set; }

    public virtual DbSet<PmsinfoDetais> PmsinfoDetais { get; set; }

    public virtual DbSet<Preferences> Preferences { get; set; }
    public virtual DbSet<ReqMerchantRecon> ReqMerchantRecon { get; set; }

    public virtual DbSet<Store> Store { get; set; }

    public virtual DbSet<Transaction> Transaction { get; set; }

    public virtual DbSet<UnMappedDailyConfigInputEntry> UnMappedDailyConfigInputEntry { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdjustOpeningBalance>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdjustableAmount)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AsOfDate).HasColumnType("datetime");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ProfitCenter)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ApprovalComments>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.AuditId).HasColumnName("AuditID");
            entity.Property(e => e.Comment)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CommentDate).HasPrecision(0);
            entity.Property(e => e.CommentedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
        });

        modelBuilder.Entity<ApprovalPloicy>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
        });

        modelBuilder.Entity<ApprovalPloicyDetails>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ApprovalPolicyId).HasColumnName("ApprovalPolicyID");
            entity.Property(e => e.AssignedTo)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.LimitAmount).HasColumnType("decimal(14, 2)");

            entity.HasOne(d => d.ApprovalPolicy).WithMany(p => p.ApprovalPloicyDetails)
                .HasForeignKey(d => d.ApprovalPolicyId)
                .HasConstraintName("FK_ApprovalPloicyDetails_ApprovalPloicy");
        });

        modelBuilder.Entity<DailyConfigDepartment>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<DailyConfigGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.CommonMappingId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CommonMappingID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DepartmentID");
            entity.Property(e => e.IncomeSubDepartmentId).HasColumnName("IncomeSubDepartmentID");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.ParentGroupId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ParentGroupID");

            entity.HasOne(d => d.ParentGroup).WithMany(p => p.InverseParentGroup)
                .HasForeignKey(d => d.ParentGroupId)
                .HasConstraintName("FK_DailyConfigGroup_DailyConfigGroup");
        });

        modelBuilder.Entity<DailyConfigInputEntry>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.Dcid, "CLI_DCID")
                .IsClustered()
                .HasFillFactor(90);

            entity.HasIndex(e => e.CorporationId, "CorporationID").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.Status, e.SaleDate }, "IDX_DailyConfigInputEntry_CorpId_Status_SaleDate").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.StoreId, e.SaleDate }, "IX_DailyConfigInputEntry_CorpStoreDate");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.ApprovedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ApprovedDate).HasPrecision(0);
            entity.Property(e => e.AssignedTo)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CashJournalId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CashJournalID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.Dcid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DCID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); 
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.ModofiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.RevenueJournalId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("RevenueJournalID");
            entity.Property(e => e.SaleDate).HasPrecision(0);
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
            entity.Property(e => e.Weather)
                .HasMaxLength(100)
                .HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<DailyConfigInputEntryAr>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DailyConfigInputEntry_AR");

            entity.HasIndex(e => e.Darid, "CLI_DARID").IsClustered();

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAccountID");
            entity.Property(e => e.CreditRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditRefID");
            entity.Property(e => e.DaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.Darid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DARID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); ;
            entity.Property(e => e.DebitRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitRefID");
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");

            entity.HasOne(d => d.DailyConfigInput).WithMany(p => p.DailyConfigInputEntryAr)
                .HasForeignKey(d => d.DailyConfigInputId)
                .HasConstraintName("FK_DailyConfigInputEntry_AR_DailyConfigInputEntry");
        });

        modelBuilder.Entity<DailyConfigInputEntryArdetails>(entity =>
        {
            entity.ToTable("DailyConfigInputEntry_ARDetails");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CrRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CrRefID");
            entity.Property(e => e.DconfigIerevId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DConfigIERevID");
            entity.Property(e => e.Description)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.DrRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DrRefID");
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");
        });

        modelBuilder.Entity<DailyConfigInputEntryReceipt>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DailyConfigInputEntry_Receipt");

            entity.HasIndex(e => e.Drid, "CLI_DRID").IsClustered();

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAccountID");
            entity.Property(e => e.CreditRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditRefID");
            entity.Property(e => e.DaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.DebitRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitRefID");
            entity.Property(e => e.Drid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DRID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); ;
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");

            entity.HasOne(d => d.DailyConfigInput).WithMany(p => p.DailyConfigInputEntryReceipt)
                .HasForeignKey(d => d.DailyConfigInputId)
                .HasConstraintName("FK_DailyConfigInputEntry_Receipt_DailyConfigInputEntry");
        });

        modelBuilder.Entity<DailyConfigInputEntryReceiptDetails>(entity =>
        {
            entity.HasKey(e => e.Id).IsClustered(false);

            entity.ToTable("DailyConfigInputEntry_ReceiptDetails");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CrRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CrRefID");
            entity.Property(e => e.DconfigCashId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DConfigCashID");
            entity.Property(e => e.Description)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.DrRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DrRefID");
            entity.Property(e => e.RefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("RefID");
        });

        modelBuilder.Entity<DailyConfigInputEntryRevenue>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DailyConfigInputEntry_Revenue");

            entity.HasIndex(e => e.Drvid, "CLI_DRVID").IsClustered();

            entity.HasIndex(e => e.DailyConfigInputId, "DailyInputID").HasFillFactor(90);

            entity.HasIndex(e => e.DailyConfigInputId, "IDX_DailyConfigInputEntry_Revenue_DailyConfigInputID_01162022").HasFillFactor(90);

            entity.HasIndex(e => e.LineId, "IDX_DailyConfigInputEntry_Revenue_LineID_01162022").HasFillFactor(90);

            entity.HasIndex(e => new { e.LineId, e.CaccountId, e.DaccountId }, "LineID").HasFillFactor(90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAccountID");
            entity.Property(e => e.CreditRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditRefID");
            entity.Property(e => e.DaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.DebitRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitRefID");
            entity.Property(e => e.Drvid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DRVID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); ;
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");

            entity.HasOne(d => d.DailyConfigInput).WithMany(p => p.DailyConfigInputEntryRevenue)
                .HasForeignKey(d => d.DailyConfigInputId)
                .HasConstraintName("FK_DailyConfigInputEntry_Revenue_DailyConfigInputEntry");

            entity.HasOne(d => d.Line).WithMany(p => p.DailyConfigInputEntryRevenue)
                .HasForeignKey(d => d.LineId)
                .HasConstraintName("FK_DailyConfigInputEntry_Revenue_DailyConfigLine");
        });

        modelBuilder.Entity<DailyConfigInputEntryRevenueDetails>(entity =>
        {
            entity.HasKey(e => e.Id).IsClustered(false);

            entity.ToTable("DailyConfigInputEntry_RevenueDetails");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.DconfigIerevId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DConfigIERevID");
            entity.Property(e => e.Description)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.RefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("RefID");

            entity.HasOne(d => d.DconfigIerev).WithMany(p => p.DailyConfigInputEntryRevenueDetails)
                .HasForeignKey(d => d.DconfigIerevId)
                .HasConstraintName("FK_DailyConfigInputEntry_RevenueDetails_DailyConfigInputEntry_Revenue");
        });

        modelBuilder.Entity<DailyConfigInputEntryStatistics>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DailyConfigInputEntry_Statistics");

            entity.HasIndex(e => e.Dsid, "CLI_DSID").IsClustered();

            entity.HasIndex(e => e.DailyConfigInputId, "DailyInputID").HasFillFactor(90);

            entity.HasIndex(e => e.DailyConfigInputId, "IDX_DailyConfigInputEntry_Statistics_DailyConfigInputID").HasFillFactor(90);

            entity.HasIndex(e => new { e.LineId, e.CaccountId, e.DaccountId }, "LineID").HasFillFactor(90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAccountID");
            entity.Property(e => e.DaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.Dsid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DSID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); ;
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");

            entity.HasOne(d => d.DailyConfigInput).WithMany(p => p.DailyConfigInputEntryStatistics)
                .HasForeignKey(d => d.DailyConfigInputId)
                .HasConstraintName("FK_DailyConfigInputEntry_Statistics_DailyConfigInputEntry");
        });

        modelBuilder.Entity<DailyConfigInputEntryStatisticsDetails>(entity =>
        {
            entity.HasKey(e => e.Id).IsClustered(false);

            entity.ToTable("DailyConfigInputEntry_StatisticsDetails");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.DconfigIesdid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DConfigIESDID");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DailyConfigLine>(entity =>
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.Dlid, "CLI_DLID")
                .IsClustered()
                .HasFillFactor(90);

            entity.HasIndex(e => new { e.CreditAccountId, e.DebitAccountId, e.EnableNegative, e.EnableAdroravg, e.SourceType, e.SourceId, e.Status }, "Composite").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.CreditAccountId, e.Status }, "IDX_DailyConfigLine_CorpID_CreditAccountID_Status").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.DepartmentId, e.CreditAccountId }, "IDX_DailyConfigLine_CorpID_DeptID_CreditAccountID").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.Status, e.StoreId }, "IDX_DailyConfigLine_CorporationID_Status");

            entity.HasIndex(e => new { e.CreditAccountId, e.Status }, "IDX_DailyConfigLine_CreditAccountID_Status_Multi_SKDB").HasFillFactor(90);

            entity.HasIndex(e => new { e.DepartmentId, e.CreditAccountId }, "IDX_DailyConfigLine_DepartmentID_CreditAccountID_Multi_SKDB").HasFillFactor(90);

            entity.HasIndex(e => new { e.DepartmentId, e.CreditAccountId }, "IDX_DailyConfigLine_DepartmentID_CreditAccountID_SKDB").HasFillFactor(90);

            entity.HasIndex(e => e.DepartmentId, "IDX_DailyConfigLine_DepartmentID_Multi_SKDB");

            entity.HasIndex(e => e.RoomType, "IDX_DailyConfigLine_RoomType");

            entity.HasIndex(e => e.Status, "IDX_DailyConfigLine_Status_Multi");

            entity.HasIndex(e => new { e.CreditAccountId, e.Status }, "IDX_DailyconfigLine_CreditAccountID_Status_SKDB").HasFillFactor(90);

            entity.HasIndex(e => e.Order, "NonClusteredIndex-20220110-083835");

            entity.HasIndex(e => e.Status, "Status");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AdjustLedgerNetId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AdjustLedgerNetID");
            entity.Property(e => e.ArledgerType).HasColumnName("ARLedgerType");
            entity.Property(e => e.ArnetType).HasColumnName("ARNetType");
            entity.Property(e => e.CommonMappingId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CommonMappingID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreditAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditAccountID");
            entity.Property(e => e.CreditCardTypId)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.DebitAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitAccountID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DepartmentID");
            entity.Property(e => e.Dlid)
                .ValueGeneratedOnAdd()
                .HasColumnName("DLID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); 
            entity.Property(e => e.EnableAdroravg).HasColumnName("EnableADRORAVG");
            entity.Property(e => e.GroupId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("GroupID");
            entity.Property(e => e.IsVacantRooms).HasColumnName("isVacantRooms");
            entity.Property(e => e.LaborStatisticsParentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LaborStatisticsParentID");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");
            entity.Property(e => e.StatisticsCalculationType).HasColumnName("statisticsCalculationType");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");

            entity.HasOne(d => d.Department).WithMany(p => p.DailyConfigLine)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_DailyConfigLine_DailyConfigDepartment");

            entity.HasOne(d => d.Group).WithMany(p => p.DailyConfigLine)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("FK_DailyConfigLine_DailyConfigGroup");
        });

        modelBuilder.Entity<DailyConfigVerification>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DailyConfigInputId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");
        });

        modelBuilder.Entity<DailySaleDefaults>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DepartmentID");
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.GroupId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("GroupID");
            entity.Property(e => e.GroupName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ItemName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");
            entity.Property(e => e.ParentGroupName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TargetDescription)
                .HasMaxLength(2000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DsCashCheckFilterReq>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DsCashCh__3214EC27D3634D78");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ReqId).HasColumnName("ReqID");
            entity.Property(e => e.Value)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DsdepositInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DSDepositInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Comments)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.Difference).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DsdepositId).HasColumnName("DSDepositID");
            entity.Property(e => e.SaleDate).HasColumnType("datetime");

            entity.HasOne(d => d.Dsdeposit).WithMany(p => p.DsdepositInfo)
                .HasForeignKey(d => d.DsdepositId)
                .HasConstraintName("FK_DSDepositInfo_DSDepositInfo");
        });

        modelBuilder.Entity<DsdepositInfoDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DSDepositInfoDetails");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DailySalesReceiptId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailySalesReceiptID");
            entity.Property(e => e.Difference).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DsdepositInfoId).HasColumnName("DSDepositInfoID");
            entity.Property(e => e.JournalEntryId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");
            entity.Property(e => e.LineName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SaleDate).HasColumnType("datetime");

            entity.HasOne(d => d.DsdepositInfo).WithMany(p => p.DsdepositInfoDetails)
                .HasForeignKey(d => d.DsdepositInfoId)
                .HasConstraintName("FK_DSDepositInfoDetails_DSDepositInfo");
        });

        modelBuilder.Entity<Dsdeposits>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DSDeposits");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ApprovedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.AssignedTo)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.AttachmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AttachmentID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.Difference).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Memo)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ReqId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ReqID");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalDeposited).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<DummyDailyConfigInputEntry>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.ApprovedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ApprovedDate).HasPrecision(0);
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasPrecision(0);
            entity.Property(e => e.DailyInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyInputID");
            entity.Property(e => e.ModifiedDate).HasPrecision(0);
            entity.Property(e => e.ModofiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.RequestId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("RequestID");
            entity.Property(e => e.SaleDate).HasPrecision(0);
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
            entity.Property(e => e.Weather)
                .HasMaxLength(100)
                .HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<DummyDailyConfigInputEntryArreceipt>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DummyDailyConfigInputEntry_ARReceipt");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaacoountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAAcoountID");
            entity.Property(e => e.CreditRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditRefID");
            entity.Property(e => e.DaaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.DebitRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitRefID");
            entity.Property(e => e.Did)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DID");
            entity.Property(e => e.RequestId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("RequestID");
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("SourceID");
        });

        modelBuilder.Entity<DummyDailyConfigInputEntryRevStat>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DummyDailyConfigInputEntry_RevStat");

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CAccountID");
            entity.Property(e => e.CreditRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CreditRefID");
            entity.Property(e => e.DaccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DAccountID");
            entity.Property(e => e.DailyConfigInputId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DailyConfigInputID");
            entity.Property(e => e.DebitRefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DebitRefID");
            entity.Property(e => e.Did)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("LineID");
            entity.Property(e => e.RequestId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("RequestID");
        });

        modelBuilder.Entity<DummyPmscorpMappingDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("DummyPMSCorpMappingDetails");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountDescription)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Cgs)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("CGS");
            entity.Property(e => e.Credit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Debit).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DepartmentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("DepartmentID");
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.PmscorpMappingId).HasColumnName("PMSCorpMappingId");
            entity.Property(e => e.PmscurrencyType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PMSCurrencyType");
            entity.Property(e => e.PmsmappingId).HasColumnName("PMSMappingId");
            entity.Property(e => e.RequestId)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("RequestID");
            entity.Property(e => e.Seq)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SEQ");
            entity.Property(e => e.TransactionType)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<JournalEntry>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("PK_t_journalEntry_id")
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable(tb => tb.HasTrigger("UpDateTransNumber"));

            entity.HasIndex(e => e.Jid, "CLI_JID").IsClustered();

            entity.HasIndex(e => e.CorporationId, "CorporationID").HasFillFactor(90);

            entity.HasIndex(e => new { e.CorporationId, e.EntryDate }, "IDX_JournalEntry_CorporationID_EntryDate").HasFillFactor(90);

            entity.HasIndex(e => e.EntryDate, "IDX_JournalEntry_Entrydate_SKDB").HasFillFactor(90);

            entity.HasIndex(e => new { e.Id, e.EntryDate, e.EntryNumber, e.Status, e.SourceId, e.SourceType, e.BillDate, e.ParentSourceType }, "IX_JournalEntry_filter").HasFillFactor(90);

            entity.HasIndex(e => e.SourceType, "SourceType").HasFillFactor(90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AuthCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BillDate).HasPrecision(0);
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate)
                .HasPrecision(0)
                .HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DepositId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DepositID");
            entity.Property(e => e.EntryDate).HasPrecision(0);
            entity.Property(e => e.EntryNumber)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasComment("check------------------check no,\r\nbill payment----------check no,\r\nDCP--------------------null,\r\nFranchise fee---------Ref. Num,\r\nLoans------------------check no,\r\nGas Bill----------------check no,\r\nReceipts--------------check no,\r\nCustomer receipt---check no,\r\nFund transfer-------Entry no,\r\nBill Entry-------------Bill no,\r\ninvoice---------------invoice no,\r\nwage cost-----------wage cost name,\r\npaychecks-----------null,\r\nadhoc payment----check no,\r\ntax payment-------check no,\r\nother payment----check no,\r\njournal--------------entry no,\r\nYear End Process--null        \r\n");
            entity.Property(e => e.IsMailSent).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Jid)
                .ValueGeneratedOnAdd()
                .HasColumnName("JID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); ;
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.ParentId)
                .HasMaxLength(18)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength()
                .HasComment("paychecks,\r\npayment fund transfer")
                .HasColumnName("ParentID");
            entity.Property(e => e.PaymentMethodId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PaymentMethodID");
            entity.Property(e => e.PaytokenId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("PaytokenID");
            entity.Property(e => e.RefId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("RefID");
            entity.Property(e => e.ReferenceMode)
                .HasDefaultValueSql("(NULL)")
                .HasComment(" 1--Cash ,\r\n 2--Check,\r\n 3-- ACHDebit,\r\n 4---DirectDeposit,\r\n 5---ACHReceipt,\r\n 6---CreditCardCredit,\r\n 7---LoanCheck,\r\n 8---WireTransfer\r\n\r\n");
            entity.Property(e => e.SettlementDate).HasPrecision(0);
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength()
                .HasComment("Paychecks-----wagecostID,\r\nEft--------BankDepositID,\r\nSales--------BankDepositID,\r\nBankDeposit--------BankDepositID,\r\nPayrollagencypayment----wagecostID\r\n\r\n\r\n\r\n\r\n\r\n\r\n")
                .HasColumnName("SourceID");
            entity.Property(e => e.SourceType)
                .HasDefaultValueSql("(NULL)")
                .HasComment("Journal SourceTypes-\r\n11----checks(General Payments),\r\n12----LoanRepayment,\r\n13----Eft,\r\n14----DCP,\r\n15----Paybill,\r\n16----Paycheck,\r\n17----Adhoc payment,\r\n18----Tax payment,\r\n19----Payrollagency payment,\r\n20----Journal,\r\n21----Bill,\r\n22----Invoice,\r\n23----Gas purchase,\r\n24----Wage cost,\r\n32----Receipt,\r\n33---InvoiceReceipt,\r\n34----BankDeposit,\r\n35---PFTransfer,\r\n36---PFReceived,\r\n41-----FundTransferTransferredTo,\r\n42-----PaymentFundTransfer,\r\n43-----SalesFundsTransfer,\r\n44-----GasBill,\r\n45-----BusinessCreditCard,\r\n46-----BillAdjustment,\r\n47-----BillDiscount,\r\n48-----InvoiceReceiptAdjustment,\r\n49-----InvoiceReceiptDiscount,\r\n50-----ICAFunds,\r\n54-----GasBillAdjustment,\r\n55-----GasBillDiscount,\r\n56-----DailyBankDeposit,\r\n57-----PeriodicBankDeposit,\r\n58-----DailyBankDepositShortage,\r\n59-----CCAdjustment,\r\n60-----GasPurchaseJournal,\r\n61-----GPProduct,\r\n62-----GPTax,\r\n63-----GPNetAmount,\r\n64-----SalesDunkInJournalEntry,\r\n65-----SalesGasJournalEntry,\r\n66-----SalesJournalPurpose,\r\n67-----DailyCardSalesJournal,\r\n68-----SalesJournalMotel1,\r\n69-----SalesJournalMotel2,\r\n70-----StoreSettings,\r\n72-----CustOrVendorCentral,\r\n73-----YearEndProcess,\r\n74-----CCFee,\r\n75-----StoredValue,\r\n76-----ReconcileAlterEntry,\r\n77-----DCPReceipt,\r\n78----MoneyInAndOut,\r\n79----DCPPaymentImport,\r\n100---RecGenPayment,\r\n101---RecJournal,\r\n102---RecBill,\r\n103---RecInvoice,\r\n104---RecReceipt,\r\n105---JournalImport,\r\n106---DCRImport\r\n");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("(NULL)")
                .HasComment(" 0---InActive,\r\n 1---Active,\r\n 2---Void,\r\n 3---Delete,\r\n1000----wagecost(PayrollJournalEntryStatus),\r\n1100-----paychecks(PayrollJournalEntryStatus),\r\n1010-----adhoc payment(PayrollJournalEntryStatus),\r\n1001-----tax payment(PayrollJournalEntryStatus),\r\n1111-----agency payment(paychecks,adhoc,tax),(PayrollJournalEntryStatus),\r\nAs of Null is aslo Active\r\n\r\n\r\n\r\n\r\n");
            entity.Property(e => e.VoidDate).HasPrecision(0);

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("t_journal_entry$fk_t_journal_entry_t_journal_entry");
        });

        modelBuilder.Entity<JournalEntryExt>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.JournalEntryId, "JournalEntryID").HasFillFactor(90);

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AdjustmentLinkId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AdjustmentLinkID");
            entity.Property(e => e.CheckMemo)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsNimbleAch).HasColumnName("IsNimbleACH");
            entity.Property(e => e.JournalEntryId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.SubTypeName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.VoidRemarks)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Locking>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.FromDate).HasPrecision(0);
            entity.Property(e => e.LockDate).HasPrecision(0);
            entity.Property(e => e.ToDate).HasPrecision(0);
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<Lookup>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("PK_m_lookup_id")
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Code)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasComment("CLT-----------clone type\r\nRL-------------Role\r\nSR-------------sales registers\r\nCS-------------cash sales\r\nNCS-----------non cash sales\r\nSP-------------sales payins\r\nMR------------Motel Register\r\nGR-------------Gas Register\r\nCA-------------Cards\r\nGAC-----------Gas Accounts\r\nMSG-----------Messages\r\nPRP-----------purpose\r\nBNS-----------Business\r\nDPL-----------Dunkin P&L\r\nConvenient-Convenient Sales\r\nCashType--- CashType\r\nMoney-------Money\r\nProducts-----Products\r\nTaxes---------Sales Taxes\r\nCND----------Credit Net Days\r\nCRD----------Cards\r\nSCLT---------Sales Cloning Types\r\n");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Order).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SourceId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasComment("Role IDs from Role Table, Constant IDs for Sales")
                .HasColumnName("SourceID");
            entity.Property(e => e.SourceMappingXml)
                .HasMaxLength(8000)
                .IsUnicode(false);
            entity.Property(e => e.SourceType)
                .HasDefaultValueSql("(NULL)")
                .HasComment("Enum------LookupSourceType-\r\n1-----------Lookup\r\n2-----------PayrollTax\r\n3-----------GasTax\r\n4-----------Account,\r\n5-----------Role,\r\n6---------- Business,\r\n7---------- MessageGroup,\r\n8--------- Purpose,\r\n9---------Clone,\r\n10--------SR \r\n11--------MR,\r\n12--------GR,\r\n13--------CS,\r\n14--------NCS,\r\n15--------SP,\r\n16--------DunkinPL,\r\n17--------User,\r\n18--------News\r\n19------Cards,\r\n20------CreditNetDays,\r\n21------Features,    \r\n22------ConvenientSales,\r\n23------Taxes,\r\n24------MoneyInAndOut,\r\n25------CashTypes,\r\n26------CloneSettings,\r\n27------Products");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("(NULL)")
                .HasComment("Enum---------Status-\r\n0---------InActive,\r\n1---------Active,\r\n3---------Delete");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });
        modelBuilder.Entity<MerchantCoapreference>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Merchant__3214EC27A7613C44");

            entity.ToTable("MerchantCOAPreference");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.AdjustmentAccountId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AdjustmentAccountID");
            entity.Property(e => e.ChargeBackAccountId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ChargeBackAccountID");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.MerchantAccountId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("MerchantAccountID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
        });

        modelBuilder.Entity<OtbforeCastDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OTBForeC__3214EC278CB7426D");

            entity.ToTable("OTBForeCastDetails");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Adr)
                .HasColumnType("decimal(14, 2)")
                .HasColumnName("ADR");
            entity.Property(e => e.OtbforeCastId).HasColumnName("OTBForeCastID");
            entity.Property(e => e.RevPar).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.Revenue).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.OtbforeCast).WithMany(p => p.OtbforeCastDetails)
                .HasForeignKey(d => d.OtbforeCastId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OTBForeCastDetails_OTBForeCastInfo");
        });

        modelBuilder.Entity<OtbforeCastIndividualDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OTBForeC__3214EC27AC15C76B");

            entity.ToTable("OTBForeCastIndividualDetails");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.OtbforeCastDetailsId).HasColumnName("OTBForeCastDetailsID");

            entity.HasOne(d => d.OtbforeCastDetails).WithMany(p => p.OtbforeCastIndividualDetails)
                .HasForeignKey(d => d.OtbforeCastDetailsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OTBForeCastIndividualDetails_OTBForeCastDetails");
        });

        modelBuilder.Entity<OtbforeCastInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OTBForeC__3214EC27C06C7517");

            entity.ToTable("OTBForeCastInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.CreatedByName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ImportRefId)
                .HasMaxLength(500)
                .HasColumnName("ImportRefID");
            entity.Property(e => e.Otbtype).HasColumnName("OTBType");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
        });

        modelBuilder.Entity<PmsclientInfo>(entity =>
        {
            entity.ToTable("PMSClientInfo");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ClientID");
            entity.Property(e => e.ClientName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UrlId).HasColumnName("UrlID");
        });

        modelBuilder.Entity<PmscorporationMappindDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("PMSCorporationMappindDetails");

            entity.HasIndex(e => e.PmscorpMappingId, "IX_PMSCorpMappingId");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountDescription)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.AccountId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("AccountID");
            entity.Property(e => e.Category)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LineId)
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.PmscorpMappingId).HasColumnName("PMSCorpMappingId");
            entity.Property(e => e.PmscurrencyType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PMSCurrencyType");
            entity.Property(e => e.PmsmappingId).HasColumnName("PMSMappingId");
            entity.Property(e => e.Seq)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("SEQ");
            entity.Property(e => e.SubCategory)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TransactionType)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.PmscorpMapping).WithMany(p => p.PmscorporationMappindDetails)
                .HasForeignKey(d => d.PmscorpMappingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PMSCorporationMappindDetails_PMSCorporationMappindDetails");
        });

        modelBuilder.Entity<PmscorporationMapping>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("PMSCorporationMapping");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AliasFacilityId)
                .HasMaxLength(600)
                .IsUnicode(false);
            entity.Property(e => e.AmountReadFrom)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength();
            entity.Property(e => e.FacilityId)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.MapId).HasColumnName("MapID");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
        });

        modelBuilder.Entity<PmsfacilityMap>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("PMSFacilityMap");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.FacilityId)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("FacilityID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.PmsclientInfoId).HasColumnName("PMSClientInfoID");
            entity.Property(e => e.PmsinfoId).HasColumnName("PMSInfoID");
        });

        modelBuilder.Entity<PmsfacilityMapDetails>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.ToTable("PMSFacilityMapDetails");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FileName)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PmsfacilityMapId).HasColumnName("PMSFacilityMapID");
        });

        modelBuilder.Entity<Pmsinfo>(entity =>
        {
            entity.ToTable("PMSINFO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Pmsname)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("PMSName");
            entity.Property(e => e.Pmstype).HasColumnName("PMSType");
        });

        modelBuilder.Entity<PmsinfoDetais>(entity =>
        {
            entity.ToTable("PMSInfoDetais");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.FileName)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("FIleName");
            entity.Property(e => e.PmsinfoId)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("PMSInfoID");
        });

        modelBuilder.Entity<Preferences>(entity =>
        {
            entity.HasKey(e => e.Id).HasAnnotation("SqlServer:FillFactor", 90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.Ardifference)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("")
                .HasColumnName("ARDifference");
            entity.Property(e => e.BankAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("BankAccountID");
            entity.Property(e => e.CoporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CoporationID");
            entity.Property(e => e.DcpbillMakePayment).HasColumnName("DCPBillMakePayment");
            entity.Property(e => e.PayrollAccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PayrollAccountID");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<ReqMerchantRecon>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Req_Merc__3214EC2700523464");

            entity.ToTable("Req_MerchantRecon");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.CorporationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.Pcid)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("PCID");
            entity.Property(e => e.ReqId).HasColumnName("ReqID");
        });

        modelBuilder.Entity<Store>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("PK_m_store_id")
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.Id, "m_store$store_id_UNIQUE")
                .IsUnique()
                .HasFillFactor(90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AddressId)
                .HasMaxLength(18)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength()
                .HasColumnName("AddressID");
            entity.Property(e => e.BaseRent)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("decimal(14, 2)");
            entity.Property(e => e.BookkeeperMail)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.ContactId)
                .HasMaxLength(18)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength()
                .HasColumnName("ContactID");
            entity.Property(e => e.CorporationId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CorporationID");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasColumnName("CustomerID");
            entity.Property(e => e.Deductions)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("decimal(14, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ParentStoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ParentStoreID");
            entity.Property(e => e.PcNo)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PercentageRent)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Pmstype).HasColumnName("PMSType");
            entity.Property(e => e.SaleStartDate)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("date");
            entity.Property(e => e.SalesType).HasComment("1-DayWise");
            entity.Property(e => e.Status).HasComment("Enum----Status-\r\n0-----InActive,\r\n1--- -Active,\r\n3-----Delete");
            entity.Property(e => e.StoreDateEnd)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("date");
            entity.Property(e => e.StoreDateStart)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("date");
            entity.Property(e => e.TaxEscrow)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("decimal(14, 2)");

            entity.HasOne(d => d.ParentStore).WithMany(p => p.InverseParentStore)
                .HasForeignKey(d => d.ParentStoreId)
                .HasConstraintName("FK_Store_Store");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("PK_t_transaction_id")
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.AccountId, "AccountID").HasFillFactor(90);

            entity.HasIndex(e => e.Tid, "CLI_TID").IsClustered();

            entity.HasIndex(e => new { e.AccountId, e.JournalEntryId, e.Amount, e.DebitCredit }, "IDX_Transaction_AccountID_JournalEntryID_Multi_SKDB").HasFillFactor(90);

            entity.HasIndex(e => new { e.TransactionDate, e.Status }, "IX_Transaction_Date_Status").HasFillFactor(90);

            entity.HasIndex(e => e.JournalEntryId, "JournalEntryID").HasFillFactor(90);

            entity.HasIndex(e => e.ParentId, "ParentID").HasFillFactor(90);

            entity.HasIndex(e => new { e.SourceId, e.TargetId }, "SourceID").HasFillFactor(90);

            entity.HasIndex(e => new { e.SourceType, e.TargetType }, "SourceType").HasFillFactor(90);

            entity.HasIndex(e => e.Status, "Status").HasFillFactor(90);

            entity.Property(e => e.Id)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("AccountID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.BankTransactionRefId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CostcenterId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("CostcenterID");
            entity.Property(e => e.DebitCredit).HasComment("0----Debit,\r\n1----Credit");
            entity.Property(e => e.FranchiseeId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("FranchiseeID");
            entity.Property(e => e.JournalEntryId)
                .IsRequired()
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("JournalEntryID");
            entity.Property(e => e.Memo)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.MerchantReconRefId)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("MerchantReconRefID");
            entity.Property(e => e.ParentId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ParentID");
            entity.Property(e => e.ReconStatus).HasComment("Enum-----Transaction status-\r\nReconcilation-------6,\r\nResumeReconcilation--19");
            entity.Property(e => e.ReconciliationId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ReconciliationID");
            entity.Property(e => e.ReferenceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("ReferenceID");
            entity.Property(e => e.ReferenceNumber)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Checks--------------Ref.Num,\r\nBill Payments-------Ref.Num,\r\nDCP------------------null,\r\nFranchisee fee-----null,\r\nLoans----------------Ref. Num,\r\nGas Bill--------------Ref Num,\r\nReceipts------------Ref Num,\r\nCustomer receipt-Ref Num,\r\nFund transfer------Ref Num,\r\nBill Entry------------Ref Num,\r\nInvoice--------------null,\r\nWage cost----------null,\r\nPaychecks----------checkno,\r\nAdhoc payment---null,\r\nTax payment-------null,\r\nOther payment----null,\r\nJournal--------------null,\r\nYearEndProcess---null\r\n");
            entity.Property(e => e.SourceId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasComment("Check-----------PurposeID/VendoriD/CustomerID/EmpID/OthersID,\r\nBill Payment----VendorID,\r\nDCP-------------null,\r\nFranchise fee----Ref.Num,\r\nLoans-----------check no,\r\nGas Bill----------check no,\r\nReceipts---------check no,\r\nCustomer receipt-CustomerID,\r\nFund transfer-----Entry no,\r\nBill Entry---------VendorID, PurposeID,\r\nInvoice-----------invoice no,\r\nWage cost--------wage cost name,\r\nPaychecks--------null,\r\nAdhoc payment---check no,\r\nTax payment-------check no,\r\nOther payment----check no,\r\nJournal------------PurposeID,\r\nYearEndProcess---null\r\n")
                .HasColumnName("SourceID");
            entity.Property(e => e.SourceType).HasComment("TST-Transaction Source Type,\r\nJST- Journal Source Type--\r\nCheck--------( TST -0,1,2,13,80),\r\nBill Payment----( JST-21, TST - 1,84,85),\r\nDCP-------( TST -0,1,2,13,80),\r\nFranchise fee----( JST-13, TST -80),\r\nLoans-----------( TST -0,1,80),\r\nReceipts------(TST- 0,1,2,13,80,87),\r\nCustomer receipt-(TST-0,22,85),\r\nFund transfer-----( TST -0,1,2,13,80,JST-41,42),\r\nBill Entry------(TST-1,80),\r\nInvoice-------(TST-0,80),\r\nWage cost-----( JST-25,26,27,28,29,30,31),\r\nPaychecks--------(TST-2)(JST-30),\r\nAdhoc payment---(TST-3) (JST-17),\r\nTax payment-------(TST-4) (JST-18),\r\nOther payment----(TST-4) (JST-19),\r\nJournal----------(TST-80,87),\r\nSales-----------(TST- 0,5,6,7,11,15,16,17,18)(JST-66)\r\n");
            entity.Property(e => e.Status).HasComment("0---InActive,\r\n1---Active,\r\n2---Void,\r\n3---Delete,\r\n4---Pending,\r\n5---Completed,\r\n6---Reconciled,\r\n7---Locked,\r\n8---RecurringReconciled,\r\n9---RecurringLocked,\r\n10--ReconcileLocked,\r\n11--RecurringReconcileLocked,\r\n12--CCFee,\r\n13--Paid,\r\n14--Unpaid,\r\n15--WithoutCC,\r\n16--NormalCC,\r\n17--ReverseCC,\r\n18--GasWithoutAmount,\r\n19--ResumeReconcile");
            entity.Property(e => e.StoreId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("StoreID");
            entity.Property(e => e.TargetId)
                .HasMaxLength(18)
                .IsFixedLength()
                .HasColumnName("TargetID");
            entity.Property(e => e.Tid)
                .ValueGeneratedOnAdd()
                .HasColumnName("TID").Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore); 
            entity.Property(e => e.TransactionDate).HasPrecision(0);
            entity.Property(e => e.XmlMemo)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.Transaction)
                .HasForeignKey(d => d.JournalEntryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_transaction$fk_t_transaction_t_journal_entry1");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("t_transaction$fk_t_transaction_t_transaction");

            entity.HasOne(d => d.Store).WithMany(p => p.Transaction)
                .HasForeignKey(d => d.StoreId)
                .HasConstraintName("t_transaction$fk_t_transaction_m_store");
        });

        modelBuilder.Entity<UnMappedDailyConfigInputEntry>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("PK__UnMapped__3214EC2719E84546")
                .HasAnnotation("SqlServer:FillFactor", 90);

            entity.HasIndex(e => e.PmscorpMapDetailsId, "IX_PMSCorpMapDetailsID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.BalanceAmount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.CreditAmount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.NetAmount).HasColumnType("decimal(14, 2)");
            entity.Property(e => e.PmscorpMapDetailsId).HasColumnName("PMSCorpMapDetailsID");
            entity.Property(e => e.PmscorpMapId).HasColumnName("PMSCorpMapID");
            entity.Property(e => e.Stats).HasColumnType("decimal(14, 2)");

            entity.HasOne(d => d.PmscorpMapDetails).WithMany(p => p.UnMappedDailyConfigInputEntry)
                .HasForeignKey(d => d.PmscorpMapDetailsId)
                .HasConstraintName("FK_pmscorpmapdetID");

            entity.HasOne(d => d.PmscorpMap).WithMany(p => p.UnMappedDailyConfigInputEntry)
                .HasForeignKey(d => d.PmscorpMapId)
                .HasConstraintName("FK_pmscorpmapID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}